/* Generated from the updated legal drafts (/tmp/privacy-legal.txt, /tmp/terms-legal.txt).
 * All operator and product facts are filled in plain language. Sections that would
 * need a lawyer's judgment (governing law, dispute venue, liability caps) are written
 * as plain operational statements instead. Regenerate rather than hand-editing when
 * the drafts change. */

export type LegalBlock = { kind: "h3" | "p"; text: string };
export type LegalSection = { num: string; title: string; blocks: LegalBlock[] };
export type LegalMetaItem = { label: string; value: string };

export const PRIVACY_META: LegalMetaItem[] = [
  { label: "Effective date", value: `September 14, 2026` },
  { label: "Last updated", value: `September 14, 2026` },
  { label: "Operator", value: `The individual operating Erudoza` },
  { label: "Privacy contact", value: `Ktr0nn@icloud.com` },
  { label: "Mailing address", value: `941 Southridge Trail, Altamonte Springs, Florida 32714` },
  { label: "Service", value: `Erudoza, available at https://Erudoza.com` },
];

export const TERMS_META: LegalMetaItem[] = [
  { label: "Effective", value: "September 14, 2026" },
  { label: "Last updated", value: "September 14, 2026" },
];

export const TERMS_INTRO: string[] = [
  `These Terms of Service (“Terms”) are a legal agreement between you and the individual operating Erudoza (“we,” “us,” or “our”). They govern your access to and use of Erudoza.com, related web applications, and any associated features, content, and services (collectively, the “Service”).`,
  `Please read these Terms carefully. If you do not agree to them, do not access or use the Service.`,
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  { num: "1", title: `Scope and who is responsible`, blocks: [
    { kind: "p", text: `This Privacy Policy explains how the individual operating Erudoza (“we,” “us,” or “our”) collects, uses, shares, stores, and protects personal information when people use Erudoza.com, the Erudoza web application, and related services, communications, and support (together, the “Service”). The individual operating Erudoza decides how and why the personal information described in this Policy is used, except where a church, club, or other organization independently decides how and why information is used. This Policy applies to coaches, club leaders, parents or guardians, students, website visitors, and anyone who contacts us. It does not apply to third-party websites or services that have their own privacy notices. Erudoza is an independent product and is not affiliated with, sponsored by, or endorsed by NAD Club Ministries, the Seventh-day Adventist Church, the Pathfinder organization, the General Conference Corporation of Seventh-day Adventists, or their affiliates. The official Pathfinder Bible Experience competition site, operated by NAD Club Ministries, is https://nadpbe.org/.` }
  ] },
  { num: "2", title: `Information we collect`, blocks: [
    { kind: "h3", text: `Coach and account information` },
    { kind: "p", text: `Account details. Name or display name, email address, username, password hash, account role, club association, and other fields collected during registration: display name, email address, club (organization) name, username, password, account role (Owner, Admin, or Student), account kind (Adult or Student), club association, and verification status. We do not store passwords in readable form. Passwords are hashed with PBKDF2-SHA-256 (100,000 iterations, unique random 16-byte salt per password). Verification and recovery. Email address, verification status, verification timestamps, password-reset requests, and security or authentication records needed for /signup, /login, and /forgot-password. Profile and settings. Display name, profile appearance (generated character art), pinned navigation, and the donation-widget preference.` },
    { kind: "h3", text: `Club and student information` },
    { kind: "p", text: `Club records. Club name, coach or leader assignments, team configuration, assigned Scripture passages, and related administrative information. Student roster. Information a coach or authorized adult enters for a student, limited to username, display name, and password (set by the coach); no email address, age band, or team field is collected. Coaches should not enter information that Erudoza does not request. Study activity. Assigned chapters or passages, study sessions, verse-by-verse progress, review history, missed items, scores, completion status, timed rehearsals, and other training metrics used to show progress and areas for practice. Student access. Students have individual accounts using coach-created credentials: a coach sets the username and password at /admin/students, and can reset passwords and activate or deactivate access. Students do not self-register and no email address is required.` },
    { kind: "h3", text: `Communications, support, and technical information` },
    { kind: "p", text: `Service communications. Verification emails, password-reset emails, account notices, support messages, and delivery information such as timestamps, delivery status, and message identifiers. Email is sent through Resend. Support information. The content of requests, attachments, and contact details when someone asks for help or reports a problem. Support is handled through email to Ktr0nn@icloud.com, handled directly by Erudoza’s operator (no third-party support provider). Device and log information. Internet Protocol address, browser and device type, operating system, referring page, requested pages, timestamps, error logs, and security events. application error logs (error names and timestamps); network-level logs are managed by Cloudflare. Cookies and local storage. Session identifiers, authentication state, preferences, progress synchronization, and other browser storage described in Section 8. Analytics. No third-party analytics are used. Erudoza currently does not offer pricing or payment processing on the public site. If payments are introduced, this Policy must be updated before collecting billing information and must name the payment provider and information flows: not applicable — Erudoza does not sell access or process payments.` }
  ] },
  { num: "3", title: `How we receive information`, blocks: [
    { kind: "p", text: `Directly from adults and users. People provide information when they create an account, verify an email address, create or manage a club, contact support, or change settings. From coaches or authorized adults. A coach may add student roster information, assign study material, and manage a student’s participation. Coaches must have authority to provide that information and must follow the children’s privacy requirements in Section 7. From use of the Service. Erudoza creates study-progress records and receives technical information when a user interacts with the Service. From service providers. Hosting, email, analytics, and support vendors may return operational information such as delivery status, error events, fraud signals, or service logs.` }
  ] },
  { num: "4", title: `How we use information`, blocks: [
    { kind: "p", text: `Provide the Service. Create and authenticate accounts; organize clubs and teams; assign passages; save study progress; run review and rehearsal features; and display progress to authorized users. Communicate. Send verification, password-reset, security, service, and support messages. Promotional email, if any, is handled as follows: Erudoza does not send marketing or promotional email — only transactional messages (verification codes, password resets, coach invitations) via Resend. Protect users and Erudoza. Detect abuse, prevent unauthorized access, troubleshoot errors, enforce applicable rules, maintain backups, and protect the integrity of the Service. Improve the Service. Understand feature performance and improve usability using Erudoza does not currently aggregate usage data for analytics. Student information is not used for advertising or unrelated profiling. Meet legal obligations. Respond to lawful requests, preserve records when required, establish or defend legal claims, and comply with applicable law.` }
  ] },
  { num: "5", title: `Why we use personal information`, blocks: [
    { kind: "p", text: `We use personal information only for the purposes described in this Policy: providing and securing the Service, managing clubs and rosters, communicating with users, and meeting our obligations. Where your permission is the basis for something — for example, a coach’s confirmation to add a student — you can withdraw it by contacting Ktr0nn@icloud.com, but withdrawal does not undo what was already done. For children under 13, see Section 7, which explains that coaches are responsible for having the needed permissions.` }
  ] },
  { num: "6", title: `When we share information`, blocks: [
    { kind: "p", text: `We disclose personal information only as described below and only to the extent reasonably necessary. Within a club. Authorized coaches and club leaders may view student roster and progress information for the teams they manage. Student visibility to teammates is teammates in a practice room can see each other’s display names and assigned roles (such as Captain or Scribe). Service providers. Vendors process information for hosting, email delivery, analytics, customer support, security, and related operations under contracts appropriate to their role. Current providers are Cloudflare (Workers, D1, and static asset hosting), Resend, Cloudflare Turnstile (bot protection), and Buy Me a Coffee (donation widget). No third-party analytics provider is used. bible-api.com supplies public-domain catalog metadata; no personal data is sent to it. Legal and safety disclosures. We may disclose information when we reasonably believe it is required by law, needed to protect rights or safety, or necessary to investigate fraud, abuse, or a security incident. Business transfers. Information may be reviewed or transferred in connection with a merger, financing, acquisition, reorganization, or sale of assets, subject to appropriate confidentiality and notice where required. With direction or consent. We may share information when an authorized user, parent, or guardian directs us to do so or gives legally valid consent. Erudoza does not sell personal information, share it for cross-context behavioral advertising, or use student information for targeted advertising.` }
  ] },
  { num: "7", title: `Children’s and teens’ privacy`, blocks: [
    { kind: "p", text: `Erudoza is a volunteer effort by a church member to help train young people for the Pathfinder Bible Experience, whose participants are typically Pathfinders ages 10–15, managed by adult coaches. Children do not create their own accounts: a coach creates a username and password for each student and manages the roster. Because coaches add young people’s information, keeping that information limited and safe is central to the Service.` },
    { kind: "h3", text: `Adult control and authorization` },
    { kind: "p", text: `Coach and club-leader accounts are for adults. A coach who adds a young person represents that the coach is the young person’s parent or legal guardian, or is an authorized church, club, or educational representative with permission to provide the student’s information and manage their participation. Erudoza does not currently operate a separate parental notice-and-consent system; the coach is responsible for having the needed permissions from parents or guardians before adding a child. If Erudoza learns that a child’s information was added without the required permission, the information will be removed within 30 days of a verified report to Ktr0nn@icloud.com.` },
    { kind: "h3", text: `What we collect about minors` },
    { kind: "p", text: `Erudoza limits student information to what is reasonably necessary for training and club administration. Requested roster fields are username, display name, and password. Study records may include assigned passages, attempts, review needs, scores, completion status, and rehearsal activity. We do not ask minors to provide full address, phone number, precise location, photos, video, or open chat. A child’s participation will not be conditioned on providing more personal information than is reasonably necessary for the activity. Coaches should use a first name, nickname, or internal identifier instead of a full legal name whenever the product supports this: the student display name is coach-entered free text.` },
    { kind: "h3", text: `Parent and guardian rights` },
    { kind: "p", text: `A verified parent or guardian of a child under 13 may request to: Review. See the personal information collected from or about the child. Delete. Ask us to delete the child’s personal information, subject to narrow legal or security exceptions. Stop collection. Refuse or withdraw consent for further collection, use, or disclosure. Limit disclosure. Direct us not to share the child’s information except as needed to provide the Service, where applicable. Requests may be sent to Ktr0nn@icloud.com. We will verify the requester’s identity and relationship to the child using by confirming control of the account’s email address or the coach’s confirmation of the relationship. We will respond within 30 days. Withdrawing consent may require deactivating the child’s access or removing the child from the club.` },
    { kind: "h3", text: `Coach responsibilities` },
    { kind: "p", text: `Coaches must provide parents or guardians with this Policy and any required direct notice before adding a child’s information. Coaches must not upload sensitive or unnecessary information, and must promptly remove students who no longer participate. Erudoza will provide coaches with the admin pages at /admin/students to edit a display name, reset a password, or activate/deactivate an account; for anything else, email Ktr0nn@icloud.com and instructions at the in-app wiki at https://erudoza.com/wiki and Ktr0nn@icloud.com. If we learn that personal information from a child under 13 was collected without required authorization or consent, we will suspend the relevant access, notify the responsible adult where appropriate, and delete the information within 30 days, unless law requires retention.` }
  ] },
  { num: "8", title: `Cookies and local storage`, blocks: [
    { kind: "p", text: `Erudoza uses cookies, local storage, or similar browser technologies to keep users signed in, protect sessions, remember preferences, preserve study state, and understand whether the Service is working. The current inventory is a first-party session cookie (__Host-erudoza.session; HttpOnly, Secure, SameSite=Lax; 8-hour expiry) for sign-in; first-party local storage for the donation-widget dismissed state and pinned navigation; and first-party session storage for in-progress practice drafts (cleared on sign-out). Strictly necessary technologies. Used for authentication, security, load balancing, fraud prevention, and core functionality. Blocking them may prevent the Service from working. Preference technologies. Remember UI preferences such as the donation-widget dismissed state, pinned navigation, and profile appearance in first-party browser storage. Analytics technologies. Erudoza does not use optional analytics cookies. Optional analytics must not be enabled for children without a lawful basis and any required consent. Users can control browser storage through their browser settings and not currently offered. Deleting storage may sign the user out or reset preferences.` }
  ] },
  { num: "9", title: `Data retention and deletion`, blocks: [
    { kind: "p", text: `Account, club, roster, and study-progress information is kept for as long as the account or club remains active, because that history is the Service (coaches review past progress to plan practice). Sign-in sessions expire automatically after 8 hours. There is no automatic deletion schedule for account data: it is deleted when you ask. To delete an account, a club, or a student’s information, email Ktr0nn@icloud.com; deletion from active systems is completed within 30 days of a verified request. Residual copies may remain in encrypted platform backups until they rotate out.` }
  ] },
  { num: "10", title: `Security`, blocks: [
    { kind: "p", text: `We use reasonable administrative, technical, and organizational safeguards designed to protect personal information. Controls include TLS (HTTPS) for all traffic, encryption at rest by Cloudflare D1, role-based access (Owner, Admin, Student) scoped to each club’s organization, HttpOnly Secure SameSite session cookies, unique password salts, and rate-limited sign-in and invitation flows. Cloudflare provides platform-level network protections for hosting. Erudoza is operated by one person; there is no separate security team or formal incident-response vendor. Vendors are limited to Cloudflare (hosting and security) and Resend (transactional email), used under their standard terms. No online service can guarantee absolute security. Users should protect their credentials and report suspected unauthorized access to Ktr0nn@icloud.com. If a security incident affects personal information, we will investigate and provide notices as required by applicable law.` }
  ] },
  { num: "11", title: `Choices and privacy rights`, blocks: [
    { kind: "p", text: `Depending on location and applicable law, a person may have the right to access, correct, delete, restrict, object to processing, obtain a portable copy, withdraw consent, or appeal a decision about a privacy request. Parents and guardians have the additional rights described in Section 7 for children under 13. Submit a request to Ktr0nn@icloud.com with enough information to identify the account or student record. We will verify identity and authority using by confirming control of the account’s email address. We will respond within 30 days, or explain any lawful extension. Authorized agents may submit requests where permitted by law, subject to we will ask for proof that the agent is authorized to act for you. If a request is denied, appeal by by replying to the email with our decision within 30 days. Users may unsubscribe from optional promotional emails through the message link or by contacting us. Account, verification, security, and service notices may still be sent while an account remains active.` }
  ] },
  { num: "12", title: `International users and transfers`, blocks: [
    { kind: "p", text: `Erudoza is operated from the United States. Personal information may be processed in countries where Erudoza or its service providers operate, including countries where Cloudflare operates its network. Those countries may have different privacy laws from the user’s location. Erudoza does not currently use standard contractual clauses or publish a transfer impact assessment. If you have questions about where information is processed, contact Ktr0nn@icloud.com.` }
  ] },
  { num: "13", title: `Region-specific disclosures`, blocks: [
    { kind: "p", text: `Erudoza is a small, free service operated by one person in the United States to help train young people for the Pathfinder Bible Experience. It does not currently publish region-specific privacy disclosures. If you have questions about your local privacy rights, contact Ktr0nn@icloud.com.` }
  ] },
  { num: "14", title: `Third-party services and links`, blocks: [
    { kind: "p", text: `The Service may link to official Pathfinder Bible Experience resources, church or club resources, Bible publishers, or other third-party sites. Their privacy practices are governed by their own notices, not this Policy. A link does not mean that the third party sponsors or endorses Erudoza. Official PBE materials may be available from official sources, but availability does not grant Erudoza a license to republish them. Erudoza does not republish official PBE guides or competition questions wholesale. The Service includes Scripture text used for training and study purposes.` }
  ] },
  { num: "15", title: `Changes to this Policy`, blocks: [
    { kind: "p", text: `We may update this Policy as the Service or law changes. We will post the updated version at https://erudoza.com/privacy and revise the “Last updated” date. For material changes, we will provide additional notice by email to the account address on file. If a change materially affects student information, coaches should confirm they still have the necessary permissions before continuing to use the Service.` }
  ] },
  { num: "16", title: `Contact us`, blocks: [
    { kind: "p", text: `Questions, privacy requests, or concerns may be directed to: Erudoza does not currently have a data protection officer or an EU/UK representative.` }
  ] }
];

export const TERMS_SECTIONS: LegalSection[] = [
  { num: "1", title: `Acceptance of these Terms`, blocks: [
    { kind: "p", text: `By creating an account, joining a club, accessing student features, or otherwise using the Service, you agree to these Terms and acknowledge the privacy practices described in the privacy policy available at https://erudoza.com/privacy (“Privacy Policy”). If you use the Service on behalf of a church, club, school, conference, organization, or other entity, you represent that you have authority to bind that entity, and “you” includes that entity. Coach accounts require the account holder to confirm they are 18 years old or older (see Section 2). Students use the Service only through a coach-managed club, with the knowledge and authorization of the responsible coach and, when required, a parent or legal guardian. Coaches must not invite or enable a young person to use the Service unless the permissions required by Section 4 have been obtained.` }
  ] },
  { num: "2", title: `Account eligibility`, blocks: [
    { kind: "p", text: `Coach accounts. A person creating or administering a coach account must be at least 18 years old and legally able to enter into these Terms. A coach acting for an organization must have that organization’s authorization. Student access. Students may be minors. Student access is available only through a coach-managed club or another account structure that Erudoza makes available. A student may use the Service only with the knowledge and authorization of the responsible coach and, when required, the student’s parent or legal guardian. No circumvention. You may not misstate your age, role, identity, authority, or relationship to a club or student in order to create or use an account.` }
  ] },
  { num: "3", title: `What Erudoza provides`, blocks: [
    { kind: "p", text: `Erudoza is a Scripture-study and training service designed to support Pathfinder Bible Experience (“PBE”) preparation. Features may include verse-by-verse learning, review activities, timed team practice, club management, passage assignments, and progress information that helps coaches identify where students may need additional practice. Erudoza is a supplemental training tool. It does not replace official PBE rules, official study materials, local safeguarding procedures, adult supervision, or the judgment of a parent, guardian, coach, church, club, school, conference, or other organization responsible for participating youth. We do not currently offer paid plans or payment functionality through the Service. If we later introduce fees, subscriptions, purchases, or other paid features, we will present the applicable price and any additional payment terms before charging you.` }
  ] },
  { num: "4", title: `Accounts, coaches, and youth safeguarding`, blocks: [
    { kind: "p", text: `4.1 Account security You must provide accurate, current information and keep it updated. You are responsible for safeguarding your password and other sign-in credentials, for activity under your account, and for promptly notifying us at Ktr0nn@icloud.com if you suspect unauthorized access. Do not share coach credentials with students or other unauthorized people. 4.2 Coach responsibilities Official PBE participation includes Pathfinders ages 10–15, so student users are expected to include minors. A coach who creates a club, invites or adds students, assigns study material, or views progress acts as the administrator of that club. The coach is responsible for: Authority and consent. Having authority to administer the club and obtaining any consent, notice, or permission required from a parent, legal guardian, church, club, school, conference, or other organization before adding a student or processing the student’s information. Accurate rosters. Adding only students who are eligible and authorized to participate, keeping club information current, and removing access promptly when a student leaves or authorization ends. Data minimization. Providing only information reasonably needed to use the Service and avoiding sensitive personal information unless Erudoza expressly requests it and the disclosure is lawful and authorized. Appropriate supervision. Supervising youth use, following applicable safeguarding policies, and ensuring that communications and activities are appropriate for minors. Access control. Limiting student progress information to adults who have a legitimate need to see it and preventing unauthorized sharing, screenshots, exports, or publication. Legal compliance. Complying with applicable child privacy, education, safeguarding, recordkeeping, and consent laws and with the rules of the coach’s organization. 4.3 Parent and guardian rights A parent or legal guardian may contact us at Ktr0nn@icloud.com to ask about a minor’s account, request correction or deletion, withdraw consent where applicable, or raise a safeguarding concern. We may need to verify identity and authority before acting. Our handling of personal information is further described in the Privacy Policy. 4.4 No unsupervised adult–student channel Unless Erudoza expressly provides and describes a supervised messaging feature, the Service is not intended to create a private, unsupervised communication channel between an adult and a student. Users must not use account names, profile fields, club content, or other features to evade safeguarding rules or contact restrictions.` }
  ] },
  { num: "5", title: `Acceptable use`, blocks: [
    { kind: "p", text: `You may use the Service only for lawful Scripture study, PBE training, club administration, and other purposes that Erudoza authorizes. You must respect other users, the safety of minors, intellectual property rights, and the security of the Service. You may not, and may not help another person to: Harass, bully, threaten, exploit, groom, sexualize, or otherwise endanger a minor or any other person. Upload, display, transmit, or link to content that is unlawful, abusive, hateful, sexually explicit, invasive of privacy, deceptive, or otherwise harmful. Collect, expose, sell, publish, or misuse a student’s identity, contact details, credentials, study records, or other personal information. Impersonate another person or organization, falsely claim authority over a club or student, or misrepresent affiliation with Erudoza or any religious or youth organization. Attempt to gain unauthorized access to accounts, clubs, systems, or data; probe or bypass security; introduce malicious code; or interfere with the Service. Scrape, crawl, harvest, index, copy, or extract data from the Service by automated means except as expressly authorized in writing by Erudoza. Reverse engineer, decompile, disassemble, or attempt to discover source code or nonpublic systems, except where applicable law clearly permits it. Use the Service to violate law, another person’s rights, official competition rules, or the safeguarding policies of a participating organization. Resell, sublicense, or commercially exploit the Service unless a separate written agreement with Erudoza permits it. Use another person’s account or credentials without permission, or create accounts through false, fraudulent, or automated means. If you become aware of conduct that may threaten a child’s safety, contact the appropriate parent, guardian, organization, or emergency authority as the situation requires. You may also report Service-related concerns to Ktr0nn@icloud.com. Erudoza is not an emergency service.` }
  ] },
  { num: "6", title: `User content and permissions`, blocks: [
    { kind: "p", text: `“User Content” means information or materials that a user submits, uploads, creates, or provides through the Service, such as club names, rosters, passage assignments, notes, and other content. Account data and usage information may also be personal information governed by the Privacy Policy. As between you and Erudoza, you retain any rights you have in your User Content. You grant Erudoza a nonexclusive, worldwide, royalty-free license to host, store, reproduce, process, display, and transmit User Content only as reasonably necessary to operate, secure, support, and improve the Service; comply with law; and enforce these Terms. This license ends when the content is deleted from active systems, subject to reasonable backup, legal, security, and record-retention requirements. You represent that you have the rights and permissions needed to provide User Content and to grant this license. Do not upload confidential, copyrighted, or personal information unless you are authorized to do so and it is appropriate for the Service. If you send ideas, suggestions, or feedback about Erudoza, you grant us a perpetual, worldwide, royalty-free right to use that feedback without restriction or compensation, but we do not acquire ownership of your unrelated User Content.` }
  ] },
  { num: "7", title: `Erudoza intellectual property`, blocks: [
    { kind: "p", text: `The Service, including its software, design, interfaces, graphics, text, compilations, and other materials provided by Erudoza, is owned by or licensed to the individual operating Erudoza and is protected by intellectual property and other laws. Subject to these Terms, Erudoza grants you a limited, personal, nonexclusive, nontransferable, revocable right to use the Service for its intended purposes. “Erudoza,” its logos, and associated branding are trademarks or brand assets of the individual operating Erudoza. You may not use them in a way that suggests sponsorship, endorsement, partnership, or official status without prior written permission. If you believe content on the Service infringes your copyright or other rights, contact Ktr0nn@icloud.com with enough detail for us to identify the material and evaluate the claim. We may request additional information required by applicable law.` }
  ] },
  { num: "8", title: `Independent service; no official affiliation`, blocks: [
    { kind: "p", text: `Erudoza is an independent training tool. It is not affiliated with, authorized by, sponsored by, or endorsed by the General Conference Corporation of Seventh-day Adventists, the North American Division of Seventh-day Adventists, NAD Club Ministries, the Pathfinder organization, Pathfinder Bible Experience, or any related church, conference, club-ministry, or Pathfinder entity. Official PBE information and competition requirements are published separately, including at https://nadpbe.org/. Users are responsible for checking the current official rules, assigned Bible passages, eligibility requirements, schedules, and instructions. If Erudoza content differs from an official source, the official source controls for competition purposes. “PATHFINDER and DESIGN” is a registered trademark of the General Conference Corporation of Seventh-day Adventists. Erudoza claims no ownership in that mark or in third-party names, logos, patches, designs, or branding. The Service will not use Pathfinder names, logos, designs, patches, uniforms, branding, or other protected identifiers without the trademark owner’s prior written permission. Users may not upload or use those identifiers in a commercial or misleading manner or imply that Erudoza is an official Pathfinder product. The official PBE How-to Guide provides limited reproduction permission for local church printed matter; that permission does not authorize reproduction in an app or other publication. Unless Erudoza has separate written permission, the Service must not reproduce official guides, competition questions, answer keys, or similar protected materials wholesale. Users must not upload or distribute those materials through the Service without authorization.` }
  ] },
  { num: "9", title: `Bible text and third-party materials`, blocks: [
    { kind: "p", text: `Bible translations and related study materials may be protected by copyright and may carry translation-specific quotation and attribution rules. The Service includes text from the New King James Version (NKJV), copyright © Thomas Nelson, provided for training and study purposes. Erudoza is not a monetized service and does not sell access, subscriptions, or services. Erudoza identifies the Bible translations used in the Service at the Scripture library at /admin/content (labeled “NKJV library”) and the Team Practice simulation setup screen, which shows the translation in use. Users may not upload, copy, publish, or distribute Bible text, official PBE content, images, music, or other third-party material unless they have permission or a valid legal right to do so. Third-party names and materials remain the property of their respective owners. Their appearance in the Service does not imply endorsement, and Erudoza does not grant users any rights in third-party materials.` }
  ] },
  { num: "10", title: `Privacy and student information`, blocks: [
    { kind: "p", text: `Our Privacy Policy at https://erudoza.com/privacy explains what information we collect, why we collect it, how we use and disclose it, how long we keep it, and the choices available to users, parents, and guardians. The Privacy Policy is incorporated into these Terms by reference. Coaches must not use the Service as a substitute for their organization’s required consent, notice, recordkeeping, or safeguarding process. Where applicable law requires verifiable parental consent or another authorization before collecting or using a minor’s personal information, the coach and sponsoring organization must obtain that authorization before creating or activating the student’s access, unless Erudoza expressly states in writing that it performs that step. Do not enter medical information, government identifiers, financial information, precise location, private counseling information, or other highly sensitive data into the Service unless Erudoza expressly requests it for a documented feature and the disclosure is lawful and authorized.` }
  ] },
  { num: "11", title: `Availability, support, and changes to the Service`, blocks: [
    { kind: "p", text: `We work to keep the Service useful and available, but we do not guarantee uninterrupted or error-free operation. The Service may be unavailable because of maintenance, security events, network or hosting failures, updates, third-party services, or circumstances beyond our reasonable control. We may add, modify, suspend, or discontinue features. When reasonably practical, we will provide notice of a material change that significantly reduces existing functionality. We may also set reasonable technical or usage limits to protect users, minors, data, and system reliability. Support is available through Ktr0nn@icloud.com. Any response targets or service levels apply only if stated in a separate written agreement.` }
  ] },
  { num: "12", title: `Disclaimers`, blocks: [
    { kind: "p", text: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE.” ERUDOZA DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, QUIET ENJOYMENT, AND WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. Erudoza does not warrant that the Service will be uninterrupted, secure, complete, accurate, or free of harmful components; that study progress will be preserved without loss; that use will improve competition results; or that content matches current official PBE rules or source materials. Users must verify official requirements independently. Nothing in these Terms excludes a warranty, guarantee, or right that cannot lawfully be excluded. Some jurisdictions do not allow certain disclaimers, so parts of this section may not apply to you.` }
  ] },
  { num: "13", title: `Limitation of liability`, blocks: [
    { kind: "p", text: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE INDIVIDUAL OPERATING ERUDOZA WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, GOODWILL, DATA, USE, OR BUSINESS OPPORTUNITY, ARISING OUT OF OR RELATING TO THE SERVICE OR THESE TERMS, EVEN IF ADVISED THAT SUCH DAMAGES ARE POSSIBLE. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE TOTAL AGGREGATE LIABILITY OF THE INDIVIDUAL OPERATING ERUDOZA FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE SERVICE OR THESE TERMS WILL NOT EXCEED THE AMOUNT YOU PAID ERUDOZA FOR THE SERVICE DURING THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO LIABILITY. These limitations apply regardless of the form or theory of liability, but they do not limit liability that cannot lawfully be limited, including any liability that applicable law requires to remain unlimited. Because some jurisdictions do not allow certain liability limitations, some of this section may not apply to you.` }
  ] },
  { num: "14", title: `Indemnification`, blocks: [
    { kind: "p", text: `To the extent permitted by law, if you are an adult coach, organization, or other person legally able to give this indemnity, you agree to defend, indemnify, and hold harmless the individual operating Erudoza from claims, losses, liabilities, damages, judgments, costs, and reasonable legal fees arising from or related to: Your violation of these Terms or applicable law. Your User Content or your misuse of another person’s information or intellectual property. Your administration of a club or student account, including a failure to obtain required authority, notice, consent, or parental permission. Your safeguarding decisions, communications, or conduct involving a student or other user. Your false representation that you are authorized to act for a person, club, church, school, conference, or other organization. Erudoza may control the defense of a covered claim, and you agree to cooperate reasonably. You may not settle a claim in a way that admits fault by or imposes obligations on Erudoza without our prior written consent. This section does not require a minor to provide an indemnity that is unenforceable under applicable law.` }
  ] },
  { num: "15", title: `Suspension and termination`, blocks: [
    { kind: "p", text: `You may stop using the Service at any time. You may request account closure through by emailing Ktr0nn@icloud.com. A coach is responsible for removing student access when participation or authorization ends. Account closure and deletion requests are handled as described in the Privacy Policy and may be subject to legal, security, backup, and record-retention requirements. We may restrict, suspend, or terminate access, remove content, or take other reasonable protective action if we believe that: These Terms, applicable law, or another person’s rights have been violated. An account, club, or activity may threaten a minor, another user, the Service, or data security. Use is fraudulent, abusive, unauthorized, or creates material legal or operational risk. We are required to act by law, court order, or a valid request from a competent authority. Continuing to provide the Service is no longer reasonably practicable. When appropriate and legally permitted, we will provide notice and an opportunity to respond. We may act immediately where necessary to protect a minor, prevent harm, secure the Service, or comply with law. Provisions that by their nature should survive termination will survive, including ownership, licenses already needed for lawful retention, disclaimers, liability limits, indemnification, disputes, and general terms.` }
  ] },
  { num: "16", title: `Resolving disputes`, blocks: [
    { kind: "p", text: `16.1 Contact us first Before filing a formal claim, you and Erudoza agree to make a good-faith effort to resolve the dispute informally. Send a written notice to Ktr0nn@icloud.com describing your name and contact information, the relevant account or club without including a student password, the facts of the dispute, and the relief requested. Erudoza will send notices to the email address associated with your account. The parties will attempt informal resolution for 30 days after receipt of the notice. 16.2 Further steps If the dispute is not resolved informally, either party may pursue the remedies available to them. 16.3 Rights that cannot be waived Nothing in these Terms prevents a user from reporting concerns to a regulator, child-protection authority, law-enforcement agency, or other government body.` }
  ] },
  { num: "17", title: `If part of these Terms cannot be enforced`, blocks: [
    { kind: "p", text: `If any part of these Terms cannot be enforced where you live, the rest of the Terms still apply.` }
  ] },
  { num: "18", title: `Changes to these Terms`, blocks: [
    { kind: "p", text: `We may update these Terms to reflect changes to the Service, law, security practices, or our operations. We will post the updated Terms and change the “Last updated” date above. If a change is material, we will provide additional notice by email to the account address on file before the change takes effect when reasonably practicable. Your continued use of the Service after updated Terms take effect means you accept them. If you do not agree to an update, you must stop using the Service. A parent, guardian, coach, or organization may need to renew consent or authorization if a change materially affects youth accounts or the handling of student information.` }
  ] },
  { num: "19", title: `General terms`, blocks: [
    { kind: "p", text: `Entire agreement. These Terms, the Privacy Policy, and any additional terms expressly presented for a feature form the entire agreement between you and Erudoza regarding the Service, unless a separate signed agreement states otherwise. Severability. If a provision is found unenforceable, it will be enforced to the maximum extent permitted and the remaining provisions will remain in effect. No waiver. A failure to enforce a provision is not a waiver of the right to enforce it later. Assignment. You may not assign or transfer these Terms without our prior written consent. We may assign them in connection with a merger, acquisition, financing, corporate reorganization, sale of assets, or by operation of law, subject to applicable privacy and consumer-protection requirements. No third-party beneficiaries. Except where these Terms expressly state otherwise, they do not create rights for a person who is not a party to them. Electronic communications. You agree that notices, disclosures, and records relating to the Service may be provided electronically to the email address associated with your account, subject to applicable law. Headings. Headings are for convenience and do not limit the meaning of these Terms.` }
  ] },
  { num: "20", title: `Contact information`, blocks: [
    { kind: "p", text: `Questions about these Terms: Ktr0nn@icloud.com Safety or youth-account concerns: Ktr0nn@icloud.com Privacy requests: Ktr0nn@icloud.com Copyright or intellectual-property notices: Ktr0nn@icloud.com Legal notices: Ktr0nn@icloud.com Mailing address: 941 Southridge Trail, Altamonte Springs, Florida 32714` }
  ] }
];
