import { useState } from "react";
import { ConfirmationDialog } from "../ui/ConfirmationDialog";
import { AppIcon } from "../AppIcon";
import { Badge, Button, HelpTip, HonorArtwork, Input, LinkButton, LoadingState, EmptyState, Notice, PageHeader, Panel, ProgressMeter, Select, Textarea, WeeklyProgressStrip } from "../ui";
import "../../styles/design-reference.css";

const colors = [
  ["Page", "--er-paper"], ["Surface", "--er-card"], ["Navy", "--er-ink-navy"],
  ["Teal", "--er-teal"], ["Attention", "--er-coral"], ["Border", "--er-border"],
] as const;
const navigation = [["principles", "Principles"], ["colors", "Colors"], ["typography", "Typography"], ["actions", "Actions"], ["forms", "Forms"], ["feedback", "Feedback"], ["honors", "Honors"], ["structure", "Structure"]] as const;

export function DesignSystemPage() {
  const [difficulty, setDifficulty] = useState("Standard");
  const [notice, setNotice] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  return <div className="design-reference">
    <PageHeader title="Erudoza design system" help="One visual language for coach and student. These are the same components used throughout the app." action={<LinkButton to="/admin" variant="secondary">Back to overview</LinkButton>} />
    <nav className="design-reference-nav" aria-label="Design system sections">{navigation.map(([id, label]) => <a href={`#${id}`} key={id}>{label}</a>)}</nav>
    <Panel id="principles"><h2>Shared styles for PBE training</h2><p>Use the shared colors and controls for Scripture study, coach setup and team practice. Keep the Erudoza emblem and approved artwork.</p><ul className="design-principles"><li><strong>Consistent by default</strong><p>One component for each recurring action, field, surface and state.</p></li><li><strong>Purpose before decoration</strong><p>Illustration belongs in branded moments. Tables and forms have clear surfaces.</p></li><li><strong>Comfortable to use</strong><p>Readable labels, 44px controls, keyboard focus and responsive layouts.</p></li></ul></Panel>
    <Panel id="colors"><h2>Colors</h2><p>Use semantic tokens. Page-specific styles should never introduce another palette.</p><div className="design-swatches">{colors.map(([label, token]) => <div key={token}><div className="design-swatch" style={{ background: `var(${token})` }} /><strong>{label}</strong><code>{token}</code></div>)}</div><p className="design-caption">Navy for text and navigation. Teal for primary actions, selections and progress. Attention and status colors always come with text.</p></Panel>
    <Panel id="typography"><h2>Typography</h2><div className="design-type"><div><span>Page title · 32px</span><p className="design-type-page">Training HQ</p></div><div><span>Section title · 22px</span><p className="design-type-section">Your training plan</p></div><div><span>Body · 15px</span><p>Review your assigned Scripture before team practice.</p></div><div><span>Caption · 12px</span><small>Difficulty applies to future sessions.</small></div></div><blockquote className="design-scripture">Know the passage. Prepare for PBE.</blockquote><p className="design-caption">The interface uses the platform sans serif. Scripture and brand lettering use the reading serif. Data uses tabular numerals.</p></Panel>
    <Panel id="actions"><h2>Actions</h2><p>Primary for the next step, secondary for alternatives, and quiet text actions for supporting tasks.</p><div className="design-component-row"><Button onClick={() => setNotice(true)}>Save example <AppIcon name="arrow" /></Button><Button variant="secondary" onClick={() => setNotice(false)}>Reset example</Button><LinkButton variant="ghost" to="/admin/seasons">View seasons</LinkButton><Button variant="ghost" className="ds-button-quiet" onClick={() => setNotice(true)}>Quiet action</Button><Button disabled>Saving…</Button></div>{notice && <Notice tone="success">Example saved locally. No season data was changed.</Notice>}<pre><code>{'<Button type="submit" disabled={pending}>Save plan</Button>\n<LinkButton to="/student/progress" variant="secondary">View progress</LinkButton>'}</code></pre></Panel>
    <Panel id="forms"><h2>Forms and choices</h2><form className="design-form" onSubmit={event => event.preventDefault()}><label>Season name<Input placeholder="e.g. Daniel · Autumn 2026" /></label><label>Book<Select defaultValue="DAN"><option value="DAN">Daniel</option><option value="JOS">Joshua</option></Select></label><label className="design-form-wide">Study notes<Textarea placeholder="Optional notes for this example" /></label><fieldset className="design-form-wide"><legend>Training difficulty</legend><div className="design-choices">{["Foundation", "Standard", "Advanced"].map(level => <label className="ds-choice" key={level}><Input type="radio" name="reference-difficulty" checked={difficulty === level} onChange={() => setDifficulty(level)} /><strong>{level}</strong></label>)}</div></fieldset><label>Invalid example<Input aria-invalid="true" aria-describedby="reference-error" placeholder="Season name" /><span id="reference-error" className="design-error">Enter a season name.</span></label><label>Unavailable field<Input value="Already saved" disabled readOnly /></label></form><pre><code>{'<label>Season name<Input required /></label>\n<Notice tone="danger">Name the problem and how to recover.</Notice>'}</code></pre></Panel>
    <Panel id="feedback"><h2>Status and feedback</h2><div className="design-component-row"><Badge>Draft</Badge><Badge tone="info">Passages ready</Badge><Badge tone="success">Active</Badge><Badge tone="warning">Review needed</Badge><Badge tone="danger">Due</Badge></div><LoadingState label="Loading your passages…" /><EmptyState title="No assignments yet" description="Your coach will add a study plan here." /><div className="design-feedback"><Notice tone="info">Sessions already started keep their original difficulty.</Notice><Notice tone="success">Your changes have been saved.</Notice><Notice tone="danger">Unable to save. Check your connection and try again.</Notice></div><div className="design-component-row"><Button variant="secondary" onClick={() => setDialogOpen(true)}>Preview dialog</Button><details className="design-disclosure"><summary>How disclosure works</summary><p>Use progressive disclosure for optional detail. Keep the main action visible.</p></details></div><h3>Section help<HelpTip label="About section help">Detail messages live in this tooltip box. Tap the question mark to read them; Escape or an outside tap closes it.</HelpTip></h3><p className="design-caption">PageHeader takes <code>help</code> for the same pattern beside page titles.</p>{dialogOpen && <ConfirmationDialog title="A focused decision" description="Confirmation dialogs keep actions in fixed positions, support Escape and restore keyboard focus. This example changes no app data." confirmLabel="Confirm example" onCancel={() => setDialogOpen(false)} onConfirm={() => setDialogOpen(false)} />}</Panel>
    <Panel id="structure"><h2>Structure and rhythm</h2><p>24px between sections, 24px inside panels, and 12px control corners. Page headings align to the content. Coach tabs and student navigation share the same colors and type.</p><div className="ds-table-scroll"><table className="ds-table"><caption className="design-caption">Component usage</caption><thead><tr><th>Pattern</th><th>Shared component</th><th>Use</th></tr></thead><tbody><tr><td>Page heading</td><td>PageHeader</td><td>Title, description, primary action</td></tr><tr><td>Section help</td><td>HelpTip</td><td>Detail message in a tooltip beside a heading</td></tr><tr><td>Content surface</td><td>Panel</td><td>Related content or a single task</td></tr><tr><td>Action</td><td>Button / LinkButton</td><td>Mutation / navigation</td></tr><tr><td>Input</td><td>Input / Select / Textarea</td><td>Labeled form controls</td></tr><tr><td>Feedback</td><td>Badge / Notice</td><td>Status / recovery or confirmation</td></tr></tbody></table></div><p className="design-caption">Defaults are light to preserve the approved theme. Motion is limited to short state transitions and respects reduced-motion preferences.</p></Panel>
    <Panel id="honors"><h2>Honors and recorded progress</h2><p>Illustrative component examples. Product screens show the learner’s saved evidence.</p><div className="design-component-row"><HonorArtwork src="/assets/training/exact-recall-160.webp" alt="Exact Recall patch example" /><HonorArtwork src="/assets/training/reference-ready-160.webp" alt="Unearned Reference Ready patch example" muted /></div><h3>Daily drill example</h3><ProgressMeter label="Example drill" value={3} max={8} /><WeeklyProgressStrip week={{ weekStartLocalDate: "2026-09-07", timeZone: "UTC", target: 4, completedDays: 2, days: Array.from({ length: 7 }, (_, index) => ({ localDate: `2026-09-${String(index + 7).padStart(2, "0")}`, credited: index < 2, isToday: index === 2 })) }} /><p>Pointer motion stays within seven degrees and moves only artwork. Reduced motion, touch and hidden tabs remain still. Missed days preserve recorded progress.</p></Panel>
  </div>;
}
