import {useState} from 'react';
import {useInfiniteQuery,useQueryClient} from '@tanstack/react-query';
import {pbeDisputeApi,type PbeDispute} from '../../api/practice';
import {useAuth} from '../../auth/AuthContext';
import {Badge,Button,Input,LinkButton,LoadingState,Notice,PageHeader,Panel,Textarea,useToast} from '../../components/ui';
import './practice.css';
export function DisputeQueue(){
 const {me}=useAuth(),cache=useQueryClient(),toast=useToast();
 const queue=useInfiniteQuery({queryKey:['pbe-disputes',me?.organizationId,me?.userId],initialPageParam:'',queryFn:({pageParam})=>pbeDisputeApi.queue(pageParam),getNextPageParam:page=>page.nextCursor??undefined,enabled:me?.kind==='Adult'});
 async function replay(id:string){try{for(let n=0;n<20;n++){const result=await pbeDisputeApi.replay(id);if(result.status==='Ready'){await queue.refetch();toast.success('Rubric correction saved. Practice evidence is up to date.');return;}}toast.success('Rubric correction saved. More practice evidence remains to update.');}catch(e){toast.danger(e instanceof Error?e.message:'The correction is saved. Retry updating its practice evidence.');}}
 async function saved(d:PbeDispute){toast.info('Rubric correction saved. Updating practice evidence…');await queue.refetch();await cache.invalidateQueries({queryKey:['practice']});await replay(d.id);}
 return <div className="practice-page"><PageHeader title="PBE answer reviews" description="Review the saved rubric and source, then record points for each part." action={<LinkButton variant="secondary" to="/admin/practice">Back to Team Practice</LinkButton>}/><p>Students can finish and start another practice while these answers await review. Solo reviews remain available when Team Practice is disabled.</p>{queue.isPending&&<LoadingState label="Loading answer reviews…"/>}{queue.isError&&<Notice tone="danger">{queue.error.message}<Button variant="secondary" onClick={()=>void queue.refetch()}>Retry</Button></Notice>}{queue.data?.pages.every(p=>!p.items.length)&&<Panel><h2>No pending reviews or evidence updates</h2><p>Saved corrections stay with their original answers.</p></Panel>}{queue.data?.pages.flatMap(p=>p.items).map(d=><ReviewCard key={d.id} dispute={d} onSaved={saved} onReplay={replay} onRefresh={async()=>{await queue.refetch();}}/>)}{queue.hasNextPage&&<Button variant="secondary" disabled={queue.isFetchingNextPage} onClick={()=>void queue.fetchNextPage()}>Load more reviews</Button>}</div>;
}
function ReviewCard({dispute:d,onSaved,onReplay,onRefresh}:{dispute:PbeDispute;onSaved:(d:PbeDispute)=>Promise<void>;onReplay:(id:string)=>Promise<void>;onRefresh:()=>Promise<void>}){
 const [parts,setParts]=useState(d.originalPointsByPart),[reason,setReason]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('');
 async function resolve(){setPending(true);setError('');try{await onSaved(await pbeDisputeApi.resolve(d.id,{expectedRevision:d.revision,pointsByPart:parts,reason:reason.trim()}));}catch(e){setError(e instanceof Error?e.message:'The review changed. Refresh before trying again.');await onRefresh();}finally{setPending(false);}}
 return <Panel><Badge tone="warning">{d.activity}{d.team?` · Team ${d.team}`:''} · {d.status==='Resolved'?'Evidence update remaining':'Review pending'}</Badge><h2>{d.question.prompt}</h2><p>{d.question.reference} · Saved question version {d.questionVersion}</p><p><strong>Request:</strong> {d.reason}</p><p><strong>Submitted:</strong> {d.answers.join(' · ')||'No answer'}</p><p><strong>Source evidence:</strong> {d.sourceEvidence}</p>{d.status==='Resolved'?<><p>The rubric correction is saved. Continue updating its practice evidence.</p><Button variant="secondary" disabled={pending} onClick={()=>{setPending(true);void onReplay(d.id).finally(()=>setPending(false));}}>Continue evidence update</Button></>:<form className="practice-form" onSubmit={e=>{e.preventDefault();if(!pending&&reason.trim())void resolve();}}>{d.question.parts.map((part,i)=><label key={i}>Part {i+1} points · maximum {part.points}<Input type="number" min={0} max={part.points} step={1} required value={parts[i]} onChange={e=>setParts(old=>old.map((p,n)=>n===i?Number(e.target.value):p))}/><small>Accepted: {part.acceptedAnswers.join(' / ')} · Original score: {d.originalPointsByPart[i]}</small></label>)}<label>Reason for the correction<Textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button type="submit" disabled={pending||!reason.trim()}>{pending?'Saving correction…':'Save rubric correction'}</Button>{error&&<Notice tone="danger">{error}</Notice>}</form>}</Panel>;
}
