import { parsePbeImport } from './pbeAuthoring';
import { useRef, useState } from 'react';
import { useInfiniteQuery, useQuery, useQueryClient } from '@tanstack/react-query';
import { pbeApi, type PbeAuthorQuestion, type PbeTarget, type PracticeQuestion } from '../../api/practice';
import { Badge, Button, Input, Notice, Select, Textarea } from '../../components/ui';
import { PbeBankCoverage } from './PbeBankCoverage';
import { PbeTargetFields } from './PbeTargetFields';
import { PbeIntroductionEditor } from './PbeIntroductionEditor';
export function PbeQuestionEditor({org,season,initialLegacy}:{org:string;season:string;initialLegacy?:PracticeQuestion}){
 const cache=useQueryClient(),editor=useRef<HTMLDivElement>(null);
 const metadata=useInfiniteQuery({queryKey:['pbe',org,season,'authoring'],initialPageParam:'',queryFn:({pageParam})=>pbeApi.authoring(org,season,pageParam),getNextPageParam:p=>p.membersNextCursor??undefined});
 const targetQuery=useInfiniteQuery({queryKey:['pbe',org,season,'targets'],initialPageParam:'',queryFn:({pageParam})=>pbeApi.targets(org,season,pageParam),getNextPageParam:p=>p.nextCursor??undefined});
 const questionQuery=useInfiniteQuery({queryKey:['pbe',org,season,'questions'],initialPageParam:'',queryFn:({pageParam})=>pbeApi.questions(org,season,pageParam),getNextPageParam:p=>p.nextCursor??undefined});
 const bank=useQuery({queryKey:['pbe',org,season,'bank'],queryFn:()=>pbeApi.bank(org,season)}),introductions=useQuery({queryKey:['pbe',org,season,'introductions'],queryFn:()=>pbeApi.introductions(org,season)});
 const sources=metadata.data?.pages[0].sources??[],targets=targetQuery.data?.pages.flatMap(p=>p.items)??[],questions=questionQuery.data?.pages.flatMap(p=>p.items)??[];
 const [sourceIds,setSourceIds]=useState<string[]>([]),[label,setLabel]=useState(''),[skill,setSkill]=useState<PbeTarget['skill']>('FactualRecall'),[identity,setIdentity]=useState({id:'',version:1}),[prompt,setPrompt]=useState(initialLegacy?.prompt??''),[kind,setKind]=useState<PbeAuthorQuestion['kind']>((initialLegacy?.kind as PbeAuthorQuestion['kind'])??'ShortAnswer'),[evidence,setEvidence]=useState(initialLegacy?.evidence??''),[ordered,setOrdered]=useState(initialLegacy?.ordered??false),[parts,setParts]=useState<PbeAuthorQuestion['parts']>(initialLegacy?.parts.map(p=>({...p,acceptedAnswers:[...p.acceptedAnswers],targetId:''}))??[{targetId:'',acceptedAnswers:[''],points:1}]),[preview,setPreview]=useState<{questions:PbeAuthorQuestion[];targets:PbeTarget[]}|null>(null),[reviewed,setReviewed]=useState(false),[json,setJson]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState(''),[pending,setPending]=useState(false);
 const selected=sourceIds.flatMap(id=>sources.filter(s=>s.id===id)),eligible=targets.filter(t=>t.sourceUnitIds.every(id=>selected.some(s=>s.id===id))),reference=sourceIds.map(id=>sources.find(s=>s.id===id)?.citation).filter(Boolean).join('; ');
 const signature=JSON.stringify(sources);
 const [lastSignature,setLastSignature]=useState(signature);
 if(signature!==lastSignature){setLastSignature(signature);setSourceIds([]);setParts(ps=>ps.map(p=>({...p,targetId:''})));setPreview(null);setReviewed(false);}
 function changed(){setPreview(null);setReviewed(false);}
 async function run(work:()=>Promise<unknown>){if(pending)return;setPending(true);setError('');setSuccess('');try{await work();await cache.invalidateQueries({queryKey:['pbe',org,season]});setSuccess('Saved. Only explicitly published questions count toward coverage.');}catch(e){setError(e instanceof Error?e.message:'Could not save. Your draft has been kept.');}finally{setPending(false);}}
 function prepare(){setError('');try{
  if(parts.some(p=>!eligible.some(t=>t.id===p.targetId)))throw Error('Choose a learning target for every scoring part.');
  if(!selected.length||selected.length!==sourceIds.length||selected.some(s=>s.contentPackId!==selected[0].contentPackId))throw Error('Choose current sources from the same book or introduction.');
  const total=parts.reduce((n,p)=>n+p.points,0);if(total<1||total>8||parts.some(p=>!Number.isInteger(p.points)||p.points<1))throw Error('Use 1–8 total accuracy points.');
  if(!prompt.trim()||!evidence.trim()||parts.some(p=>!p.acceptedAnswers.some(a=>a.trim())))throw Error('Provide a prompt, source evidence and accepted answers for every part.');
  if(identity.version>2147483647)throw Error('This question reached the maximum version; create a variant with a new ID.');
  if(kind==='ExactWords'&&parts.some(p=>eligible.find(t=>t.id===p.targetId)?.skill!=='ExactWords'))throw Error('Exact words require exact-word learning targets.');
  if(kind==='TrueFalse'&&(parts.length!==1||new Set(parts[0].acceptedAnswers.map(a=>a.trim().toLowerCase())).size!==1||!['true','false'].includes(parts[0].acceptedAnswers[0].trim().toLowerCase())))throw Error('True or false needs one unambiguous true or false answer.');
  const used=eligible.filter(t=>parts.some(p=>p.targetId===t.id));if(sourceIds.some(id=>!used.some(t=>t.sourceUnitIds.includes(id))))throw Error('Every selected source needs a scoring target.');
  setPreview({targets:used,questions:[{schemaVersion:2,id:identity.id||crypto.randomUUID(),version:identity.version,contentPackId:selected[0].contentPackId,sourceUnitId:sourceIds[0],sourceUnitIds:sourceIds,sourceKind:selected[0].sourceKind,reference,evidence,kind,prompt,ordered,parts:parts.map(p=>({...p,acceptedAnswers:p.acceptedAnswers.filter(a=>a.trim())}))}]});
 }catch(e){setError((e as Error).message);}}
 function edit(q:PbeAuthorQuestion,variant:boolean){setIdentity({id:variant?'':q.id,version:variant?1:q.version+1});setSourceIds(q.sourceUnitIds);setPrompt(q.prompt);setKind(q.kind);setEvidence(q.evidence);setParts(q.parts.map(p=>({...p,acceptedAnswers:[...p.acceptedAnswers]})));setOrdered(q.ordered);changed();editor.current?.focus();}
 return <section className="pbe-bank-editor" aria-label="PBE bank preparation"><h2>PBE bank preparation</h2>{initialLegacy&&<Notice>Preparing a separate PBE question from legacy wording. Choose sources and declare targets explicitly; the original question and its history are preserved.</Notice>}<p>Choose what students should recall and write accepted answers supported by the source. Review each question before publishing. PBE points do not include a speed bonus.</p>{error&&<Notice tone="danger">{error}</Notice>}{success&&<Notice tone="success">{success}</Notice>}
 {[metadata,targetQuery,questionQuery,bank,introductions].some(q=>q.isError)&&<Notice tone="danger">PBE preparation could not load. <Button variant="secondary" onClick={()=>void cache.invalidateQueries({queryKey:['pbe',org,season]})}>Retry PBE preparation</Button></Notice>}
 {bank.data&&<PbeBankCoverage coveredSources={bank.data.sourceUnitCount-bank.data.missingSourceUnitIds.length} assignedSources={bank.data.sourceUnitCount} singleVariantTargets={bank.data.singleVariantTargets} uncoveredTargets={bank.data.uncoveredTargets} onAdd={()=>editor.current?.focus()}/>}
 {metadata.data&&<><p>PBE training is {metadata.data.pages[0].pbeEnabled?'enabled':'disabled'} for this season. This setting controls whether students can start PBE practice. You can still see missing question coverage when practice is enabled.</p><Button variant="secondary" disabled={pending} onClick={()=>void run(()=>pbeApi.enabled(org,season,!metadata.data!.pages[0].pbeEnabled))}>{metadata.data.pages[0].pbeEnabled?'Disable PBE training':'Enable PBE training'}</Button></>}
 <div ref={editor} tabIndex={-1} className="practice-editor"><h3>Prepare a PBE question</h3><label>PBE source<Select value={sourceIds[0]??''} onChange={e=>{setSourceIds(e.target.value?[e.target.value]:[]);setParts(ps=>ps.map(p=>({...p,targetId:''})));changed();}}><option value="">Choose approved source</option>{sources.map(s=><option key={s.id} value={s.id}>{s.chapter===null?'Book introduction · ':''}{s.citation}</option>)}</Select></label>
 {selected.length>0&&<><blockquote>{selected.map(s=>s.canonicalText).join('\n')}</blockquote><p>{reference}</p><details className="ds-disclosure"><summary>Additional source passages</summary>{sources.filter(s=>s.contentPackId===selected[0].contentPackId&&s.id!==sourceIds[0]).map(s=><label key={s.id}><Input type="checkbox" checked={sourceIds.includes(s.id)} onChange={e=>{setSourceIds(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id));changed();}}/>{s.citation}</label>)}</details></>}
 <details className="ds-disclosure"><summary>Declare a learning target</summary><p>A target states one recall skill. Declare it before writing any question.</p><label>Target label<Input maxLength={10000} value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Target skill<Select value={skill} onChange={e=>setSkill(e.target.value as PbeTarget['skill'])}><option value="FactualRecall">Factual recall</option><option value="ExactWords">Exact words</option></Select></label><Button disabled={pending||!selected.length||!label.trim()} onClick={()=>void run(()=>pbeApi.declare(org,season,[{id:crypto.randomUUID(),sourceUnitIds:sourceIds,label,skill}]))}>Save learning target</Button></details>
 <label>PBE question kind<Select value={kind} onChange={e=>{setKind(e.target.value as PbeAuthorQuestion['kind']);changed();}}>{['ShortAnswer','List','ExactWords','TrueFalse'].map(k=><option key={k}>{k}</option>)}</Select></label><label>PBE prompt<Textarea value={prompt} maxLength={10000} onChange={e=>{setPrompt(e.target.value);changed();}}/></label><label>Source evidence excerpt<Textarea value={evidence} maxLength={10000} onChange={e=>{setEvidence(e.target.value);changed();}}/></label>
 {parts.map((p,i)=><fieldset key={i}><legend>Scoring part {i+1}</legend><PbeTargetFields targets={eligible} selectedTargetId={p.targetId||null} onSelect={id=>{setParts(ps=>ps.map((v,j)=>i===j?{...v,targetId:id}:v));changed();}}/><label>Part {i+1} accepted wordings<Textarea value={p.acceptedAnswers.join('\n')} onChange={e=>{setParts(ps=>ps.map((v,j)=>i===j?{...v,acceptedAnswers:e.target.value.split('\n')}:v));changed();}}/></label><label>Part {i+1} accuracy points<Input type="number" min={1} max={8} step={1} value={p.points} onChange={e=>{setParts(ps=>ps.map((v,j)=>i===j?{...v,points:Number(e.target.value)}:v));changed();}}/></label><Button variant="ghost" disabled={parts.length===1} onClick={()=>{setParts(ps=>ps.filter((_,j)=>i!==j));changed();}}>Remove PBE part {i+1}</Button></fieldset>)}
 <Button variant="secondary" disabled={parts.length>=8} onClick={()=>{setParts(ps=>[...ps,{targetId:'',acceptedAnswers:[''],points:1}]);changed();}}>Add PBE scoring part</Button><label>Require answer order<Select value={String(ordered)} onChange={e=>{setOrdered(e.target.value==='true');changed();}}><option value="false">Any order</option><option value="true">Required order</option></Select></label><p>Version {identity.version}{identity.id?' · New rubric version of an existing question':' · New question identity'}</p><Button onClick={prepare}>Preview PBE question</Button>
 {targetQuery.hasNextPage&&<Button variant="secondary" onClick={()=>void targetQuery.fetchNextPage()}>Load more learning targets</Button>}</div>
 <details className="ds-disclosure"><summary>Import PBE JSON</summary><label>PBE import document<Textarea rows={6} value={json} onChange={e=>{setJson(e.target.value);changed();}}/></label><p>Provide schema version 2 questions and their targets. Up to 100 questions and 500 targets are checked together. If any are invalid, none are saved.</p><Button variant="secondary" onClick={()=>{try{const value=parsePbeImport(json);if(value.questions.some(q=>q.sourceUnitIds.some(id=>!sources.some(s=>s.id===id))))throw Error('PBE imports must use current approved season sources.');setPreview(value);setError('');}catch(e){setError((e as Error).message);}}}>Preview PBE import</Button></details>
 {preview&&<section><h3>PBE draft preview</h3>{preview.questions.map((q,i)=><article key={i}><strong>{q.prompt}</strong><p>{q.reference}</p><blockquote>{q.sourceUnitIds.map(id=>sources.find(s=>s.id===id)?.canonicalText).join("\n")}</blockquote><p>{q.evidence}</p><p>{q.parts?.map(p=>`${p.acceptedAnswers?.join(' / ')} · ${p.points} points`).join('; ')}</p></article>)}<Button disabled={pending} onClick={()=>void run(async()=>{await pbeApi.import(org,season,preview.questions,preview.targets);setPreview(null);})}>Save PBE drafts</Button></section>}
 <h3>Saved PBE question versions</h3><label><Input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the canonical source, targets and accepted answers for publication</label>{!questions.length&&<p>No PBE questions yet. Declare a target and prepare a question above.</p>}{questions.map(r=><details className="ds-disclosure" key={r.id}><summary>{r.question.prompt} · v{r.question.version} · {r.published?'Published version':'Draft'}</summary><p>{r.publishedHeadVersion===r.question.version?"Current published head":r.published?"Historical published version":`Draft · current published version: ${r.publishedHeadVersion??"none"}`}</p><p>{r.question.reference}</p><p>{r.question.evidence}</p><p>{r.question.parts.map(p=>p.acceptedAnswers.join(' / ')).join('; ')}</p><Badge>Version {r.question.version}</Badge><div className="practice-actions"><Button variant="secondary" onClick={()=>edit(r.question,true)}>Create wording variant</Button><Button variant="secondary" disabled={r.question.version===2147483647} onClick={()=>edit(r.question,false)}>Correct rubric in new version</Button>{!r.published&&<Button disabled={pending||!reviewed} onClick={()=>void run(()=>pbeApi.publish(org,season,r.question.id,r.question.version))}>Publish PBE version {r.question.version}</Button>}</div></details>)}{questionQuery.hasNextPage&&<Button variant="secondary" onClick={()=>void questionQuery.fetchNextPage()}>Load more PBE question versions</Button>}
 <PbeIntroductionEditor org={org} season={season} books={metadata.data?.pages[0].selectedBookKeys??[]} members={metadata.data?.pages.flatMap(p=>p.members)??[]} introductions={introductions.data??[]} run={run}/>{metadata.hasNextPage&&<Button variant="secondary" onClick={()=>void metadata.fetchNextPage()}>Load more season members</Button>}
 </section>;
}
