import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { practiceApi, type SimulationConfig, type SimulationMaterial, type PracticeRoom } from '../../api/practice';
import { Badge, Button, Input, LoadingState, Notice, Panel, Select } from '../../components/ui';
import { TrainingDialog } from '../../components/ui/TrainingDialog';
import { ProfileAvatar } from '../profile/ProfileAvatar';
export function defaultSimulation(material:SimulationMaterial,creatorId:string):SimulationConfig{return {version:1,scope:'AllAssigned',preset:'FullEvent',bookKeys:material.books.map(book=>book.key),chapters:[],includeScripture:true,includeIntroductions:material.introductionsAvailable,timeMultiplier:1,halfTime:true,discussion:'InPerson',audioPresenterId:creatorId};}
export function SimulationEditor({material,creatorId,initial,initialSize=6,initialCount=90,members=[],pending,onSave,readOnly=false,blocked=false}:{material:SimulationMaterial;creatorId:string;initial?:SimulationConfig;initialSize?:number;initialCount?:number;members?:PracticeRoom['members'];pending:boolean;onSave:(config:SimulationConfig,size:number,count:number)=>void;readOnly?:boolean;blocked?:boolean}){
 const [tab,setTab]=useState('Material'),[config,setConfig]=useState(()=>initial?{...initial,scope:initial.scope??(initial.chapters.length?'SelectedChapters':'AllAssigned')}:defaultSimulation(material,creatorId)),[size,setSize]=useState(initialSize),[count,setCount]=useState(initialCount),[selected,setSelected]=useState(initial?.scope==='SelectedChapters'||(!initial?.scope&&Boolean(initial?.chapters.length)));
 const update=(part:Partial<SimulationConfig>)=>setConfig(value=>({...value,...part}));
 const unavailableChapters=config.chapters.filter(c=>!material.books.some(b=>b.key===c.bookKey&&b.chapters.includes(c.chapter)));
 const invalid=(!config.includeScripture&&!config.includeIntroductions)||(selected&&(!config.bookKeys.length||!config.chapters.length))||config.chapters.some(c=>!material.books.some(b=>b.key===c.bookKey&&b.chapters.includes(c.chapter)));
 return <div className="simulation-editor"><div role="tablist" aria-label="Simulation settings" className="simulation-tabs">{['Material','Timers','Team','Review'].map(name=><Button key={name} variant={tab===name?'primary':'ghost'} role="tab" tabIndex={tab===name?0:-1} onKeyDown={event=>{const tabs=['Material','Timers','Team','Review'];if(['ArrowRight','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();const index=event.key==='Home'?0:event.key==='End'?3:(tabs.indexOf(name)+(event.key==='ArrowRight'?1:3))%4;setTab(tabs[index]);const buttons=event.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('[role=tab]');buttons?.[index].focus();}}} aria-selected={tab===name} aria-controls="simulation-tab-panel" onClick={()=>setTab(name)}>{name}</Button>)}</div><div id="simulation-tab-panel" role="tabpanel" aria-label={tab}>
 <fieldset disabled={pending||readOnly||blocked} className="simulation-fields">
 {tab==='Material'&&<><h3>Choose your assigned material</h3><p>{material.translation} · Only available assigned material is included.</p><label><Input type="radio" name="scope" checked={!selected} onChange={()=>{setSelected(false);update({scope:'AllAssigned',bookKeys:material.books.map(b=>b.key),chapters:[]});}}/>Whole assigned scope</label><label><Input type="radio" name="scope" checked={selected} onChange={()=>{setSelected(true);update({scope:'SelectedChapters',bookKeys:[],chapters:[]});}}/>Selected chapters</label>{selected&&unavailableChapters.length>0&&<Notice tone="info"><p>These retained chapters are unavailable for this setup. A new room uses your assigned material until teammates join. Remove unavailable chapters and choose available ones, or explicitly choose Whole assigned scope.</p>{unavailableChapters.map(c=><div className="practice-row" key={`${c.bookKey}-${c.chapter}`}><span>{c.bookKey} {c.chapter} · Unavailable</span><Button variant="secondary" aria-label={`Remove unavailable ${c.bookKey} ${c.chapter}`} onClick={()=>{const chapters=config.chapters.filter(item=>item.bookKey!==c.bookKey||item.chapter!==c.chapter);update({chapters,bookKeys:[...new Set(chapters.map(item=>item.bookKey))]});}}>Remove unavailable chapter</Button></div>)}</Notice>}{selected&&material.books.map(book=><Panel key={book.key}><h3>{book.label}</h3><div className="simulation-chapters">{book.chapters.map(chapter=><label key={chapter}><Input type="checkbox" checked={config.chapters.some(c=>c.bookKey===book.key&&c.chapter===chapter)} onChange={e=>{const chapters=e.target.checked?[...config.chapters,{bookKey:book.key,chapter}]:config.chapters.filter(c=>c.bookKey!==book.key||c.chapter!==chapter);update({chapters,bookKeys:[...new Set(chapters.map(c=>c.bookKey))]});}}/>{book.label} {chapter}</label>)}</div></Panel>)}<label><Input type="checkbox" checked={config.includeScripture} onChange={e=>update({includeScripture:e.target.checked})}/>Include Scripture</label><label><Input type="checkbox" disabled={!material.introductionsAvailable} checked={config.includeIntroductions} onChange={e=>update({includeIntroductions:e.target.checked})}/>Include reviewed introductions</label>{!material.introductionsAvailable&&<p>No reviewed introductions are available.</p>}</>}
 {tab==='Timers'&&<><h3>Set the rehearsal pace</h3><label>Preset<Select value={config.preset} onChange={e=>{const preset=e.target.value as SimulationConfig['preset'];update({preset,timeMultiplier:1,halfTime:preset==='FullEvent'});setCount(preset==='FullEvent'?90:10);}}><option value="FullEvent">Full event</option><option value="ShortPractice">Short practice</option><option value="Custom">Custom</option></Select></label><label>Number of questions<Select disabled={config.preset==='FullEvent'} value={count} onChange={e=>{const n=Number(e.target.value);setCount(n);if(n!==90)update({halfTime:false});}}>{(config.preset==='ShortPractice'?[10,30]:[10,30,90]).map(n=><option key={n} value={n}>{n}</option>)}</Select></label><label>Response time<Select disabled={config.preset!=='Custom'} value={config.timeMultiplier} onChange={e=>update({timeMultiplier:Number(e.target.value) as 1|1.5|2})}><option value={1}>Standard · based on question points</option><option value={1.5}>1.5 × standard time</option><option value={2}>2 × standard time</option></Select></label><label><Input type="checkbox" disabled={count!==90||config.preset!=='Custom'} checked={config.halfTime} onChange={e=>update({halfTime:e.target.checked})}/>Five-minute halftime after question 45</label><Notice>Every question is read twice before the timer. A ten-second warning is always shown.</Notice></>}
 {tab==='Team'&&<><h3>Practice together</h3><label>Team size<Select value={size} onChange={e=>setSize(Number(e.target.value))}>{[2,3,4,5,6].map(n=><option key={n} value={n} disabled={n<members.length}>{n} students</option>)}</Select></label><label>Discussion method<Select value={config.discussion} onChange={e=>update({discussion:e.target.value as 'InPerson'|'Chat'})}><option value="InPerson">In person · discuss aloud</option><option value="Chat">In-app chat</option></Select></label><p>Your scribe submits the team answer. Everyone sees the same question and timer.</p>{members.map(member=><div className="practice-row" key={member.userId}><ProfileAvatar userId={member.userId} displayName={member.displayName} size={32}/><span>{member.displayName}</span><Badge>{[member.captain&&'Captain',member.scribe&&'Scribe',member.userId===creatorId&&'Creator'].filter(Boolean).join(' · ')||'Team member'}</Badge></div>)}{config.discussion==='InPerson'&&<label>Audio presenter<Select value={config.audioPresenterId??creatorId} onChange={e=>update({audioPresenterId:e.target.value})}>{(members.length?members:[{userId:creatorId,displayName:'You'}]).map(m=><option key={m.userId} value={m.userId}>{m.displayName}</option>)}</Select></label>}<p>Captain and scribe roles can be assigned from the team roster.</p></>}
 {tab==='Review'&&<><h3>Ready for rehearsal</h3><Notice>Answers reveal after every question. Accuracy uses the standard PBE rubric. These settings remain fixed.</Notice><dl className="practice-room-summary"><div><dt>Material</dt><dd>{config.bookKeys.map(key=>material.books.find(b=>b.key===key)?.label??key).join(', ')} · {selected?`${config.chapters.length} selected chapters`:'Whole assigned scope'}</dd></div><div><dt>Format</dt><dd>{count} questions · {size} students · {config.timeMultiplier}× timing</dd></div><div><dt>Discussion</dt><dd>{config.discussion==='InPerson'?'In person':'In-app chat'}</dd></div></dl><p>Flag an answer for coach review after it is revealed. Settings lock when the rehearsal starts.</p></>}
 </fieldset></div>{invalid&&<Notice tone="info">Choose available material and at least one source. Selected chapters cannot be empty.</Notice>}{readOnly?<Notice>Only the room creator can change setup while the room is in the lobby.</Notice>:<div className="practice-actions simulation-editor-footer"><Button disabled={pending||invalid||blocked} onClick={()=>onSave(config,size,count)}>{pending?'Saving…':'Save setup'}</Button></div>}</div>;
}
type MenuProps={org:string;seasonId:string;creatorId:string;open:boolean;onClose:()=>void;onSave:(config:SimulationConfig,size:number,count:number,baselineRevision?:number)=>void;room?:PracticeRoom;seed?:PracticeRoom;pending?:boolean;error?:string};
export function simulationSetupFingerprint(room?:PracticeRoom){return room?JSON.stringify({simulation:room.simulation,teamSize:room.teamSize,questionCount:room.questionCount,ownerId:room.ownerId,status:room.status,members:room.members.map(({userId,team,captain,scribe})=>({userId,team,captain,scribe})).sort((a,b)=>a.userId.localeCompare(b.userId))}):'';}
export function SimulationMenu(props:MenuProps){return props.open?<SimulationMenuSession {...props}/>:null;}
function SimulationMenuSession({org,seasonId,creatorId,onClose,onSave,room,seed,pending=false,error=""}:MenuProps){
 const [baseline,setBaseline]=useState(()=>room),[generation,setGeneration]=useState(0);
 const fingerprint=simulationSetupFingerprint(room);
 const stale=fingerprint!==simulationSetupFingerprint(baseline);
 const materialRoomId=room?.id;
 const material=useQuery({queryKey:['simulation-material',org,seasonId,materialRoomId,fingerprint],queryFn:()=>practiceApi.simulationMaterial(org,seasonId,materialRoomId),enabled:!!seasonId,placeholderData:previous=>previous});
 return <TrainingDialog className="ds-dialog-workspace" open title="Simulation menu" onClose={onClose} pending={pending}>{error&&<Notice tone="danger">{error}</Notice>}{stale&&<Notice tone="danger">The room setup or roster changed. Your edits are retained; reload before saving.</Notice>}{room&&room.revision!==baseline?.revision&&<Button variant="secondary" disabled={pending} onClick={()=>{setBaseline(room);setGeneration(n=>n+1);}}>Reload latest setup</Button>}{material.isPending?<LoadingState label="Loading available material…"/>:material.isError?<Notice tone="danger">{material.error.message}<Button onClick={()=>void material.refetch()}>Retry material</Button></Notice>:<SimulationEditor key={generation} material={material.data} creatorId={baseline?.ownerId??creatorId} initial={baseline?.simulation??(seed?.simulation?{...seed.simulation,audioPresenterId:creatorId}:undefined)} initialSize={baseline?.teamSize??seed?.teamSize} initialCount={baseline?.questionCount??seed?.questionCount} members={baseline?.members} pending={pending} blocked={stale||material.isFetching} readOnly={!!room&&(room.ownerId!==creatorId||room.status!=='Lobby')} onSave={(config,size,count)=>{if(!stale)onSave(config,size,count,baseline?.revision);}}/>}</TrainingDialog>;
}
