import { expect, test } from "@playwright/test";
import { login, logout } from "./helpers";
import { answerCard, type StoredSource } from "./study-source-helpers";
import type { ChallengeCard } from "../src/api/types";
test("coach activates a season and student submits a correct real activity with debug answers disabled", async ({ page }) => {
  await login(page);
  const me = await (await page.request.get("/api/v1/me")).json();
  const org = `/api/v1/organizations/${me.organizationId}`;
  const students = await (await page.request.get(`${org}/students`)).json();
  const student = students.find((item: { userName: string }) => ["daniel.student", "student.fixture"].includes(item.userName));
  expect(student).toBeTruthy();
  const library = await (await page.request.get(`${org}/library`)).json();
  const daniel = library.books.find((book: { bookKey: string }) => book.bookKey === "DAN");
  const units = await (await page.request.get(`${org}/content-packs/${daniel.contentPackId}/source-units`)).json() as StoredSource[];
  const source: string = units.find((unit: { chapter: number; verse: number }) => unit.chapter === 1 && unit.verse === 1)!.canonicalText;
  await page.goto("/admin/seasons/new");
  await page.getByTestId("season-name").fill(`E2E study ${Date.now()}`);
  await page.getByTestId("save-season").click();
  await page.getByRole("button", { name: "Choose passages", exact: true }).click();
  await page.getByRole("combobox", { name: "Add a library book" }).selectOption(daniel.contentPackId);
  await page.getByRole("button", { name: "Add book", exact: true }).click();
  await page.getByText("Advanced passage options", { exact: true }).click();
  await page.getByTestId("scope-end-chapter").selectOption("1");
  await page.getByTestId("scope-end").selectOption("1");
  await page.getByTestId("save-scope").click();
  await page.getByRole("link", { name: `Manage assignments for ${student.displayName}`, exact: true }).click();
  await page.getByRole("button", { name: "Specific verses", exact: true }).click();
  await page.getByTestId("assign-student").click();
  await expect(page.getByText("Assignment saved.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Review season" }).click();
  await page.getByTestId("activate-season").click();
  await page.getByRole("dialog").getByRole("button", { name: "Start season", exact: true }).click();
  await expect(page.getByTestId("season-status")).toHaveText("Active");
  const seasonId = new URL(page.url()).pathname.split("/").pop();
  await logout(page);
  await login(page, student.userName, process.env.ERUDOZA_E2E_PASSWORD!);
  await page.goto(`/student?seasonId=${seasonId}`);
  const cardResponse = page.waitForResponse(response => /\/api\/v1\/study\/sessions\/[^/]+\/next$/.test(response.url()));
  await page.getByTestId("start-todays-deck").click();
  const card = await (await cardResponse).json() as ChallengeCard;
  expect(card.debugAnswer).toBeFalsy();
  expect(card.tokens.filter(token => token.hidden).every(token => token.display === "____")).toBe(true);
  await expect(page.getByTestId("card-progress")).toHaveText(/1 \/ \d+/);
  await expect(page.getByTestId("submit-answer")).toBeVisible();
  await expect(page.getByTestId("debug-answer")).toHaveCount(0);
  await answerCard(page, card, units);
  await page.getByTestId("submit-answer").click();
  await expect(page.getByTestId("challenge-feedback").getByRole("heading", { name: "Well remembered" })).toBeVisible();
  await expect(page.getByTestId("feedback-source")).toHaveText(source);
  await expect(page.getByTestId("submit-answer")).toBeDisabled();
  await page.reload();
  await expect(page.getByTestId("challenge-feedback").getByRole("heading", { name: "Well remembered" })).toBeVisible();
  await page.getByTestId("complete-session").click();
  await expect(page).toHaveURL(/\/student\/sessions\/[^/]+\/recap/);
  await expect(page.getByText("1 correct from 1 accepted attempts", { exact: false })).toBeVisible();
  await page.getByRole("link", { name: "View current progress", exact: true }).click();
  await expect(page.getByTestId("progress-attempts")).not.toHaveText("0");
});
