import { expect, test } from "@playwright/test";
import { login, logout } from "./helpers";
import { answerCard, json, type StoredSource } from "./study-source-helpers";
import type { Assignment, ChallengeCard, SeasonScope } from "../src/api/types";
test("coach activates a season and student submits a correct real activity with debug answers disabled", async ({ page }) => {
  await login(page);
  const me = await (await page.request.get("/api/v1/me")).json();
  const org = `/api/v1/organizations/${me.organizationId}`;
  const students = await (await page.request.get(`${org}/students`)).json();
  const student = students.find((item: { userName: string }) => ["daniel.student", "student.fixture"].includes(item.userName));
  expect(student).toBeTruthy();
  const library = await (await page.request.get(`${org}/library`)).json();
  const daniel = library.books.find((book: { bookKey: string }) => book.bookKey === "DAN");
  const units = await (await page.request.get(`${org}/content-packs/${daniel.contentPackId}/source-units`)).json() as StoredSource[];
  const source: string = units.find((unit: { chapter: number; verse: number }) => unit.chapter === 1 && unit.verse === 1)!.canonicalText;
  await page.goto("/admin/seasons/new");
  await page.getByLabel("Season name", { exact: true }).fill(`E2E study ${Date.now()}`);
  await page.getByRole("checkbox", { name: "Daniel Whole book", exact: true }).check();
  await page.getByRole("button", { name: "Save & assign students →", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Student assignments", exact: true })).toBeVisible();
  const seasonId = new URL(page.url()).pathname.split("/").at(-1)!;
  const scopePath = `${org}/seasons/${seasonId}/scope`;
  const wholeBook = await json<SeasonScope>(page.request, scopePath);
  expect(wholeBook.packs).toEqual([{ contentPackId: daniel.contentPackId, includes: [{ bookKey: "DAN", startChapter: 1, startVerse: 1, endChapter: 12, endVerse: 13 }], excludes: [] }]);
  // Preserve the exact-source activity fixture through the supported existing-scope API.
  // The current planner creates whole books and retains saved custom selections.
  const singleVerse = { contentPackId: daniel.contentPackId, includes: [{ bookKey: "DAN", startChapter: 1, startVerse: 1, endChapter: 1, endVerse: 1 }], excludes: [] };
  await json(page.request, scopePath, singleVerse);
  await page.goto(`/admin/seasons/${seasonId}?step=details`);
  await expect(page.getByRole("checkbox", { name: "Daniel Saved season selection retained", exact: true })).toBeChecked();
  await page.getByRole("button", { name: "Save & assign students →", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Student assignments", exact: true })).toBeVisible();
  expect((await json<SeasonScope>(page.request, scopePath)).packs).toEqual([singleVerse]);
  await page.goto(`/admin/seasons/${seasonId}?step=students&studentId=${student.userId}`);
  await expect(page.getByText("Only the saved season selection is available.", { exact: true })).toBeVisible();
  await page.getByRole("checkbox", { name: "Chapter 1", exact: true }).check();
  await page.getByRole("button", { name: "Save assignments", exact: true }).click();
  await expect(page.getByText("Assignments saved.", { exact: true })).toBeVisible();
  const assignments = await json<Assignment[]>(page.request, `${org}/seasons/${seasonId}/assignments`);
  expect(assignments).toHaveLength(1);
  expect(assignments[0]).toMatchObject({ studentUserId: student.userId, contentPackId: daniel.contentPackId, ...singleVerse.includes[0] });
  await page.getByRole("button", { name: "Start season", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Start season", exact: true }).click();
  await expect(page.locator(".season-planner").getByText("Active", { exact: true })).toBeVisible();
  await logout(page);
  await login(page, student.userName, process.env.ERUDOZA_E2E_PASSWORD!);
  await page.goto(`/student?seasonId=${seasonId}`);
  const cardResponse = page.waitForResponse(response => /\/api\/v1\/study\/sessions\/[^/]+\/next$/.test(response.url()));
  await page.getByTestId("start-todays-deck").click();
  const card = await (await cardResponse).json() as ChallengeCard;
  expect(card.debugAnswer).toBeFalsy();
  expect(card.tokens.filter(token => token.hidden).every(token => token.display === "____")).toBe(true);
  await expect(page.getByTestId("card-progress")).toHaveText(/1 \/ \d+/);
  await expect(page.getByTestId("submit-answer")).toBeVisible();
  await expect(page.getByTestId("debug-answer")).toHaveCount(0);
  await answerCard(page, card, units);
  await page.getByTestId("submit-answer").click();
  await expect(page.getByTestId("challenge-feedback").getByRole("heading", { name: "Well remembered" })).toBeVisible();
  await expect(page.getByTestId("feedback-source")).toHaveText(source);
  await expect(page.getByTestId("submit-answer")).toBeDisabled();
  await page.reload();
  await expect(page.getByTestId("challenge-feedback").getByRole("heading", { name: "Well remembered" })).toBeVisible();
  await page.getByTestId("complete-session").click();
  await expect(page).toHaveURL(/\/student\/sessions\/[^/]+\/recap/);
  await expect(page.getByText("1 correct from 1 accepted attempts", { exact: false })).toBeVisible();
  await page.getByRole("link", { name: "View current progress", exact: true }).click();
  await expect(page.getByTestId("progress-attempts")).not.toHaveText("0");
});
