import { expect, test } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { assertNoOverflow, login, logout } from './helpers';
import { json, type StoredSource } from './study-source-helpers';
import type { ContentPack, Me, Student } from '../src/api/types';
import type { PbeQuestionRecord } from '../src/api/practice';
test('coach prepares a sparse PBE bank, versions, variants and introductions before Team Practice enablement',async({page},info)=>{
 test.setTimeout(180000);page.setDefaultTimeout(15000);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await login(page);const me=await json<Me>(page.request,'/api/v1/me'),org=`/api/v1/organizations/${me.organizationId}`;
 const pack=(await json<ContentPack[]>(page.request,`${org}/content-packs`)).find(p=>p.packKey==='dev-daniel')!;
 const sources=(await json<StoredSource[]>(page.request,`${org}/content-packs/${pack.id}/source-units`)).sort((a,b)=>a.ordinal-b.ordinal).slice(0,3);
 const username=info.project.name.startsWith('native')?'student.fixture':'daniel.student';const student=(await json<Student[]>(page.request,`${org}/students`)).find(s=>s.userName===username)!;
 const season=await json<{id:string}>(page.request,`${org}/seasons`,{name:`PBE authoring ${randomUUID()}`,yearLabel:'2026',ruleProfileKey:'PBE_STYLE_V1'});
 const range={bookKey:sources[0].bookKey,startChapter:sources[0].chapter,startVerse:sources[0].verse,endChapter:sources[2].chapter,endVerse:sources[2].verse};
 await json(page.request,`${org}/seasons/${season.id}/scope`,{contentPackId:pack.id,includes:[range],excludes:[]});
 await json(page.request,`${org}/seasons/${season.id}/assignments`,{studentUserId:student.userId,contentPackId:pack.id,type:'PrimarySpecialist',difficulty:'Standard',range});
 await json(page.request,`${org}/seasons/${season.id}/activate`,{});
 await json(page.request,`${org}/practice/enabled`,{enabled:true});
 const legacy={id:randomUUID(),version:1,contentPackId:pack.id,sourceUnitId:sources[0].id,prompt:'Legacy conversion wording',kind:'ShortAnswer',parts:[{acceptedAnswers:['Legacy reviewed answer'],points:1}],ordered:false,evidence:sources[0].canonicalText,reference:sources[0].citation};
 await json(page.request,`${org}/practice/questions/import`,{seasonId:season.id,questions:[legacy]});
 await json(page.request,`${org}/practice/enabled`,{enabled:false});
 const base=`${org}/practice/pbe/seasons/${season.id}`;
 await page.goto('/admin/practice');await page.getByLabel('Question season').selectOption(season.id);await page.getByLabel('Question format').selectOption('pbe');
 await expect(page.getByText('0 of 3 assigned passages have questions')).toBeVisible();
 await page.getByRole('combobox',{name:'PBE source',exact:true}).selectOption(sources[0].id);await expect(page.getByRole('blockquote').filter({hasText:sources[0].canonicalText})).toBeVisible();
 await page.getByText('Declare a learning target',{exact:true}).click();await page.getByLabel('Target label').fill('Opening source fact');await page.getByRole('button',{name:'Save learning target',exact:true}).click();await expect(page.getByText('1 declared targets have no published questions')).toBeVisible();
 const targets=await json<{items:{id:string}[]}>(page.request,base+'/targets');expect(targets.items).toHaveLength(1);
 await page.getByLabel('Learning target').selectOption(targets.items[0].id);await page.getByLabel('PBE prompt').fill('What opening fact is given?');await page.getByLabel('Source evidence excerpt').fill(sources[0].canonicalText);await page.getByLabel('Part 1 accepted wordings').fill('Synthetic accepted answer');
 await page.getByRole('button',{name:'Preview PBE question',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'PBE draft preview'})).toBeVisible();
 await page.getByRole('button',{name:'Save PBE drafts'}).click();await expect(page.getByText('What opening fact is given? · v1 · Draft')).toBeVisible();await expect(page.getByText('0 of 3 assigned passages have questions')).toBeVisible();
 await page.getByText('What opening fact is given? · v1 · Draft').click();await expect(page.getByRole('button',{name:'Publish PBE version 1'})).toBeDisabled();await page.getByLabel('I reviewed the canonical source, targets and accepted answers for publication').check();await page.getByRole('button',{name:'Publish PBE version 1'}).click();await expect(page.getByText('1 of 3 assigned passages have questions')).toBeVisible();await expect(page.getByText('1 targets need another question variant')).toBeVisible();
 await page.getByRole('button',{name:'Create wording variant'}).click();await page.getByLabel('PBE prompt').fill('Give the opening fact in this source.');await page.getByRole('button',{name:'Preview PBE question',exact:true}).click();await page.getByRole('button',{name:'Save PBE drafts'}).click();await page.getByText('Give the opening fact in this source. · v1 · Draft').click();await page.getByLabel('I reviewed the canonical source, targets and accepted answers for publication').check();await page.getByRole('button',{name:'Publish PBE version 1'}).click();await expect(page.getByText('0 targets need another question variant')).toBeVisible();
 let saved=await json<{items:PbeQuestionRecord[]}>(page.request,base+'/questions');expect(new Set(saved.items.map(r=>r.question.id)).size).toBe(2);const first=saved.items.find(r=>r.question.prompt==='What opening fact is given?')!;const original=JSON.stringify(first.question);
 await page.getByText('What opening fact is given? · v1 · Published version',{exact:true}).locator('..').getByRole('button',{name:'Correct rubric in new version'}).click();await page.getByLabel('Part 1 accepted wordings').fill('Synthetic accepted answer\nExplicit alternate');await page.getByRole('button',{name:'Preview PBE question',exact:true}).click();await page.getByRole('button',{name:'Save PBE drafts'}).click();saved=await json<{items:PbeQuestionRecord[]}>(page.request,base+'/questions');expect(saved.items).toHaveLength(3);expect(JSON.stringify(saved.items.find(r=>r.id===first.id)!.question)).toBe(original);expect(saved.items.find(r=>r.question.version===2)!.published).toBe(false);
 await page.getByText('Prepare a book introduction',{exact:true}).click();await page.getByLabel('Introduction book').selectOption(sources[0].bookKey);await page.getByLabel('Source edition').fill('Synthetic edition');await page.getByLabel('Introduction title').fill('Synthetic book introduction');await page.getByLabel('Introduction citation').fill('Synthetic introduction §1');await page.getByRole('combobox',{name:'Licensing',exact:true}).selectOption('approved');await page.getByLabel('Introduction text').fill('This synthetic introduction supports local authoring checks.');await page.getByRole('button',{name:'Save introduction draft'}).click();await page.getByText('Synthetic book introduction · Unreviewed').click();await page.getByRole('button',{name:'Mark source reviewed'}).click();await page.getByText('Synthetic book introduction · Reviewed').click();await page.getByLabel(student.displayName,{exact:true}).check();await page.getByRole('button',{name:'Save introduction assignments'}).click();await expect(page.getByRole('option',{name:'Book introduction · Synthetic introduction §1'})).toHaveCount(1);
 await page.getByRole('button',{name:'Enable PBE training',exact:true}).click();await expect(page.getByRole('button',{name:'Disable PBE training',exact:true})).toBeVisible();
 await page.getByRole('combobox',{name:'PBE source',exact:true}).selectOption(sources[0].id);await page.getByText('Synthetic book introduction · Reviewed',{exact:true}).click();
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await assertNoOverflow(page);await page.screenshot({path:info.outputPath(`pbe-coach-${width}.png`),fullPage:true});await page.getByRole('heading',{name:'Prepare a PBE question',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`pbe-source-form-${width}.png`)});await page.getByRole('button',{name:'Save introduction assignments',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath(`pbe-introduction-${width}.png`)});}

 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('combobox',{name:'PBE source',exact:true}).focus();await page.keyboard.press('Tab');await expect(page.locator(':focus')).toHaveCount(1);
 // Conversion is a coach action with explicit source/target mapping and publication.
 await json(page.request,`${org}/practice/enabled`,{enabled:true});await page.reload();await page.getByLabel('Question season').selectOption(season.id);await page.getByText('Legacy conversion wording · Draft').click();await page.getByRole('button',{name:'Prepare as PBE draft',exact:true}).click();await expect(page.getByLabel('PBE prompt')).toHaveValue(legacy.prompt);await expect(page.getByRole('combobox',{name:'PBE source',exact:true})).toHaveValue('');await expect(page.getByLabel('Learning target')).toHaveValue('');
 await page.getByRole('combobox',{name:'PBE source',exact:true}).selectOption(sources[0].id);await page.getByLabel('Learning target').selectOption(targets.items[0].id);await expect(page.getByLabel('Part 1 accepted wordings')).toHaveValue('Legacy reviewed answer');await page.getByRole('button',{name:'Preview PBE question',exact:true}).click();await page.getByRole('button',{name:'Save PBE drafts'}).click();await page.getByText('Legacy conversion wording · v1 · Draft').click();await expect(page.getByRole('button',{name:'Publish PBE version 1'})).toBeDisabled();await page.getByLabel('I reviewed the canonical source, targets and accepted answers for publication').check();await page.getByRole('button',{name:'Publish PBE version 1'}).click();
 const converted=(await json<{items:PbeQuestionRecord[]}>(page.request,base+'/questions')).items.find(r=>r.question.prompt===legacy.prompt)!;expect(converted.question.id).not.toBe(legacy.id);expect(converted.published).toBe(true);const legacyAfter=await json<{questions:{question:unknown}[]}>(page.request,`${org}/practice/bootstrap`);expect(legacyAfter.questions.find(r=>(r.question as {id:string}).id===legacy.id)!.question).toEqual(legacy);
 // A second active season must clear all source, target and preview state.
 const second=await json<{id:string}>(page.request,`${org}/seasons`,{name:`PBE reset ${randomUUID()}`,yearLabel:'2026',ruleProfileKey:'PBE_STYLE_V1'});await json(page.request,`${org}/seasons/${second.id}/scope`,{contentPackId:pack.id,includes:[range],excludes:[]});await json(page.request,`${org}/seasons/${second.id}/activate`,{});await page.reload();await page.getByLabel('Question format').selectOption('pbe');await page.getByLabel('Question season').selectOption(season.id);await page.getByRole('combobox',{name:'PBE source',exact:true}).selectOption(sources[0].id);await page.getByLabel('Question season').selectOption(second.id);await expect(page.getByRole('combobox',{name:'PBE source',exact:true})).toHaveValue('');await expect(page.getByLabel('Learning target')).toHaveValue('');
 await logout(page);const coachRequests:string[]=[];page.on('request',r=>{if(/\/pbe\/.*\/(authoring|targets|questions)/.test(r.url()))coachRequests.push(r.url());});await login(page,username);await page.goto('/student/practice');await expect(page.getByRole('heading',{name:'Coach question bank'})).toHaveCount(0);expect(coachRequests).toEqual([]);
 for(const endpoint of ['/authoring','/targets','/questions'])expect((await page.request.get(base+endpoint)).status()).toBe(403);
 const publicBank=await (await page.request.get(base+'/bank')).text();expect(publicBank).not.toMatch(/acceptedAnswers|Synthetic accepted answer|evidence/);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await assertNoOverflow(page);await page.screenshot({path:info.outputPath(`pbe-student-${width}.png`),fullPage:true});}expect(errors).toEqual([]);
});
