import { expect, test, type Page } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { assertNoOverflow, login, logout } from './helpers';
import { answerCard, json, type StoredSource } from './study-source-helpers';
import type { AttemptResult, ChallengeCard, ContentPack, Me, Student } from '../src/api/types';
import type { BadgeProgress, PassageJourneyPage, SessionRecap, TrainingPreferences, TrainingToday } from '../src/api/trainingTypes';

async function finishCards(page: Page, first: ChallengeCard, sources: StoredSource[], count = 8) {
  let card = first;
  const activities = new Set<string>();
  for (let index = 0; index < count; index++) {
    expect(card.sequence).toBe(index + 1);
    expect(card.total).toBe(8);
    expect(card.debugAnswer).toBeFalsy();
    activities.add(card.activityType);
    await expect(page.getByTestId('challenge-card')).toBeVisible();
    await answerCard(page, card, sources);
    const accepted = page.waitForResponse(r => r.url().endsWith(`/study/sessions/${card.sessionId}/attempts`) && r.request().method() === 'POST');
    // Enter submits the focused button, covering keyboard activation of the answer action.
    await page.getByTestId('submit-answer').focus();
    await page.keyboard.press('Enter');
    const attempt = await (await accepted).json() as AttemptResult;
    expect(attempt.isCorrect, card.activityType).toBe(true);
    await expect(page.getByTestId('challenge-feedback')).toBeVisible();
    if (index + 1 < count) {
      const next = page.waitForResponse(r => r.url().endsWith(`/study/sessions/${card.sessionId}/next`));
      await page.getByTestId('next-card').click();
      card = await (await next).json() as ChallengeCard;
    }
  }
  await page.getByTestId('complete-session').click();
  await expect(page).toHaveURL(new RegExp(`/student/sessions/${first.sessionId}/recap`));
  await expect(page.getByRole('heading', { name: 'Session recap', exact: true })).toBeVisible();
  return activities;
}

test('daily training persists full and partial recaps, unique day credit, Honors and passage evidence on either backend', async ({ page }, info) => {
  test.setTimeout(180000);
  const native = info.project.name.startsWith('native');
  const username = native ? 'student.fixture' : 'daniel.student';
  await login(page);
  const me = await json<Me>(page.request, '/api/v1/me');
  const org = `/api/v1/organizations/${me.organizationId}`;
  const packs = await json<ContentPack[]>(page.request, `${org}/content-packs`);
  const pack = packs.find(p => p.packKey === 'dev-daniel');
  expect(pack, 'Synthetic development pack must be installed by the isolated fixture').toBeTruthy();
  const sources = (await json<StoredSource[]>(page.request, `${org}/content-packs/${pack!.id}/source-units`)).sort((a, b) => a.ordinal - b.ordinal).slice(0, 3);
  expect(sources).toHaveLength(3);
  const students = await json<Student[]>(page.request, `${org}/students`);
  const student = students.find(s => s.userName === username);
  expect(student).toBeTruthy();
  const season = await json<{ id: string }>(page.request, `${org}/seasons`, { name: `Training evidence ${randomUUID()}`, yearLabel: '2026', ruleProfileKey: 'PBE_STYLE_V1' });
  const range = { bookKey: sources[0].bookKey, startChapter: sources[0].chapter, startVerse: sources[0].verse, endChapter: sources[2].chapter, endVerse: sources[2].verse };
  await json(page.request, `${org}/seasons/${season.id}/scope`, { contentPackId: pack!.id, includes: [range], excludes: [] });
  const assignment = await json<{ id: string }>(page.request, `${org}/seasons/${season.id}/assignments`, { studentUserId: student!.userId, contentPackId: pack!.id, type: 'PrimarySpecialist', difficulty: 'Standard', range });
  await json(page.request, `${org}/seasons/${season.id}/activate`, {});
  await page.goto(`/admin/seasons/${season.id}?step=review`);
  await expect(page.getByTestId('season-status')).toHaveText('Active');
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    await assertNoOverflow(page);
    await page.screenshot({ path: info.outputPath(`training-coach-${width}.png`), fullPage: true });
  }
  await logout(page);
  await login(page, username);
  const todayPath = `/api/v1/progress/me/today?seasonId=${season.id}`;
  await page.goto(`/student?seasonId=${season.id}`);
  await expect(page.getByTestId('start-todays-deck')).toBeEnabled();
  const before = await json<TrainingToday>(page.request, todayPath);
  expect(before.mission.steps.find(s => s.kind === 'Practice')?.target).toBe(8);
  const started = page.waitForResponse(r => r.url().endsWith('/api/v1/study/sessions') && r.request().method() === 'POST');
  const next = page.waitForResponse(r => /\/study\/sessions\/[^/]+\/next$/.test(r.url()));
  await page.getByTestId('start-todays-deck').click();
  const startResponse = await started;
  const startBody = startResponse.request().postDataJSON();
  const first = await (await next).json() as ChallengeCard;
  const replay = await json<{ id: string }>(page.request, '/api/v1/study/sessions', startBody);
  expect(replay).toMatchObject({ id: first.sessionId });
  const resumed = page.waitForResponse(r => r.url().endsWith(`/study/sessions/${first.sessionId}`));
  await page.reload();
  expect((await (await resumed).json()).card).toEqual(first);
  const activities = await finishCards(page, first, sources);
  expect(new URL(page.url()).searchParams.get('seasonId')).toBe(season.id);
  expect(activities).toEqual(new Set(['MissingWords', 'VerseBuilder', 'ReferenceMatch', 'WhatComesNext', 'TrueFalse']));
  const recapPath = `/api/v1/study/sessions/${first.sessionId}/recap`;
  const frozen = await json<SessionRecap>(page.request, recapPath);
  expect(frozen).toMatchObject({ version: 'training-v1', sessionId: first.sessionId, attempted: 8, correct: 8, targetCardCount: 8, fullTargetReached: true });
  expect(frozen.passageChanges.length).toBeGreaterThan(0);
  const after = await json<TrainingToday>(page.request, todayPath);
  expect(after.week.completedDays).toBe(before.week.completedDays + (before.week.days.some(d => d.isToday && d.credited) ? 0 : 1));
  expect(after.week.days.filter(d => d.isToday && d.credited)).toHaveLength(1);
  expect(after.mission.status).toBe('Complete');
  await page.getByRole('link', { name: 'Back to Training HQ', exact: true }).click();
  await expect(page.getByRole('link', { name: 'See today’s recap' })).toBeVisible();
  const another = page.waitForResponse(r => /\/study\/sessions\/[^/]+\/next$/.test(r.url()));
  await page.getByRole('link', { name: 'Practice another drill', exact: true }).click();
  const second = await (await another).json() as ChallengeCard;
  expect(second.sessionId).not.toBe(first.sessionId);
  await finishCards(page, second, sources);
  expect(await json<SessionRecap>(page.request, `/api/v1/study/sessions/${second.sessionId}/recap`)).toMatchObject({ attempted: 8, fullTargetReached: true, newlyCreditedDay: false });
  const partialNext = page.waitForResponse(r => /\/study\/sessions\/[^/]+\/next$/.test(r.url()));
  await page.getByRole('link', { name: 'Practice again', exact: true }).click();
  const partial = await (await partialNext).json() as ChallengeCard;
  await finishCards(page, partial, sources, 1);
  expect(await json<SessionRecap>(page.request, `/api/v1/study/sessions/${partial.sessionId}/recap`)).toMatchObject({ attempted: 1, fullTargetReached: false, newlyCreditedDay: false });
  expect((await json<TrainingToday>(page.request, todayPath)).week.completedDays).toBe(after.week.completedDays);
  await page.goto(`/student/sessions/${first.sessionId}/recap?seasonId=${season.id}`);
  await page.reload();
  await expect(page.getByText('8 correct from 8 accepted attempts', { exact: false })).toBeVisible();
  expect(await json<SessionRecap>(page.request, recapPath)).toEqual(frozen);
  expect(new URL(page.url()).searchParams.get('seasonId')).toBe(season.id);
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    await assertNoOverflow(page);
    await page.screenshot({ path: info.outputPath(`training-recap-${width}.png`), fullPage: true });
  }
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.getByRole('link', { name: 'View Honors', exact: true }).click();
  const honors = await json<BadgeProgress[]>(page.request, `/api/v1/progress/me/honors?seasonId=${season.id}`);
  expect(honors.length).toBeGreaterThan(0);
  const detail = page.getByRole('button', { name: `View ${honors[0].title} details`, exact: true }).first();
  await detail.click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(detail).toBeFocused();
  await page.getByRole('button', { name: 'Earned', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Earned', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'In progress', exact: true }).click();
  await assertNoOverflow(page);
  await page.goto(`/student/progress?seasonId=${season.id}`);
  await expect(page.getByRole('heading', { name: 'Your passage journey', exact: true })).toBeVisible();
  const journey = await json<PassageJourneyPage>(page.request, `/api/v1/progress/me/journey?seasonId=${season.id}`);
  expect(journey.chapters.reduce((sum, chapter) => sum + chapter.seenCount, 0)).toBeGreaterThan(0);
  await page.goto(`/student?seasonId=${season.id}`);
  await page.getByRole('button', { name: 'Change weekly goal', exact: true }).click();
  await page.getByLabel('Practice days per week').selectOption(after.preferences.weeklyTarget === 5 ? '3' : '5');
  const saved = page.waitForResponse(r => r.url().endsWith('/progress/me/preferences') && r.request().method() === 'PUT');
  await page.getByRole('button', { name: 'Save goal', exact: true }).click();
  const preference = await (await saved).json() as TrainingPreferences;
  expect(preference.pending).toBeTruthy();
  expect(new Date(preference.pending!.effectiveAtUtc).getTime()).toBeGreaterThan(Date.now());
  expect(preference.weeklyTarget).toBe(after.preferences.weeklyTarget);
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await logout(page);
  await login(page);
  const narrowed = { ...range, endChapter: sources[1].chapter, endVerse: sources[1].verse };
  const corrected = await page.request.put(`${org}/seasons/${season.id}/assignments/${assignment.id}/passage`, { data: narrowed });
  expect(corrected.ok(), `Correct assigned passage: HTTP ${corrected.status()}`).toBeTruthy();
  await logout(page);
  await login(page, username);
  await page.goto(`/student?seasonId=${season.id}`);
  const invalidated = await json<TrainingToday>(page.request, todayPath);
  expect(invalidated.mission.status).toBe('Invalidated');
  const updatedNext = page.waitForResponse(r => /\/study\/sessions\/[^/]+\/next$/.test(r.url()));
  await page.getByRole('link', { name: 'Start updated training', exact: true }).click();
  const updatedCard = await (await updatedNext).json() as ChallengeCard;
  expect(updatedCard.sessionId).not.toBe(first.sessionId);
  await expect(page.getByTestId('challenge-card')).toBeVisible();
  const recovered = await json<TrainingToday>(page.request, todayPath);
  expect(recovered.mission.status).toBe('Active');
  expect(recovered.mission.revision).toBeGreaterThan(after.mission.revision!);
  expect(recovered.mission.scopeVersion).not.toBe(after.mission.scopeVersion);
  expect(await json<SessionRecap>(page.request, recapPath)).toEqual(frozen);
  await info.attach('training-contract-evidence', { body: JSON.stringify({ backend: native ? 'native' : 'dotnet', seasonId: season.id, frozen, week: after.week, preference, honors, journey }, null, 2), contentType: 'application/json' });
});
