/* eslint-disable no-control-regex -- Exact .NET whitespace parity includes tab through carriage return. */
/** Pure ports of the five registered .NET study providers. IDs and timestamps belong to the session service. */
export type ActivityType = 'MissingWords' | 'VerseBuilder' | 'ReferenceMatch' | 'WhatComesNext' | 'TrueFalse';
export type AnswerMode = 'ExactText' | 'ShortFact' | 'SelectedChoice' | 'OrderedSequence';
export type StudyMode = 'Practice' | 'Review' | 'Simulation';
export interface SourceUnit { id: string; citationLabel: string; canonicalText: string }
export interface RuleProfile { studyAllowMultipleChoice: boolean; simulationAllowMultipleChoice: boolean; simulationAllowTrueFalse: boolean; trueFalseMaxRatio?: number }
export interface ActivityRequest { sourceUnit: SourceUnit; knowledgeUnitId: string; knowledgeUnitKind?: string; sessionId: string; sequence: number; difficulty: number; mode: StudyMode; ruleProfile: RuleProfile; nextSourceUnit?: SourceUnit | null; nextKnowledgeUnitId?: string | null; alternateSourceUnit?: SourceUnit | null; distractorCitations?: string[]; usedActivityTypes?: string[]; targetCardCount?: number }
export interface Token { text: string; hidden: boolean; index: number }
export interface Payload { citation: string; prompt: string; tokens: Token[]; difficulty: number; choices?: string[] | null }
export interface AnswerKey { canonicalAnswer: string; hiddenWords?: string[] | null }
export interface GeneratedActivity { activityType: ActivityType; providerType: string; answerMode: AnswerMode; evaluatorVersion: string; payload: Payload; answerKey: AnswerKey; sourceUnitId: string; knowledgeUnitId: string; answerSourceUnitId?: string }
export const EVALUATOR_VERSION = 'exact-text-v1';
export const MASTERY_VERSION = 'v2-skill-evidence';
// Seeded System.Random uses the compatibility subtractive generator (not unseeded xoshiro).
export class DotNetRandom {
 private values = new Array<number>(56).fill(0); private nextIndex = 0; private nextPrime = 21;
 constructor(seed: number) { const subtraction=seed===-2147483648?2147483647:Math.abs(seed|0); let mj=161803398-subtraction; this.values[55]=mj; let mk=1; for(let i=1;i<55;i++){const ii=21*i%55;this.values[ii]=mk;mk=(mj-mk)|0;if(mk<0)mk+=2147483647;mj=this.values[ii];}for(let k=1;k<5;k++)for(let i=1;i<56;i++){this.values[i]=(this.values[i]-this.values[1+(i+30)%55])|0;if(this.values[i]<0)this.values[i]+=2147483647;} }
 next(){if(++this.nextIndex>=56)this.nextIndex=1;if(++this.nextPrime>=56)this.nextPrime=1;let result=(this.values[this.nextIndex]-this.values[this.nextPrime])|0;if(result===2147483647)result--;if(result<0)result+=2147483647;this.values[this.nextIndex]=result;return result;}
}
function guidBytes(id:string){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))throw new Error('A GUID is required for the deterministic seed.');const bytes=id.replaceAll('-','').match(/../g)!.map(x=>parseInt(x,16));return [3,2,1,0,5,4,7,6,8,9,10,11,12,13,14,15].map(i=>bytes[i]);}
export function stableSeed(sourceUnitId:string,sessionId:string,sequence:number){let hash=2166136261;for(const value of [...guidBytes(sourceUnitId),...guidBytes(sessionId)])hash=Math.imul(hash^value,16777619);return Math.imul(hash^sequence,16777619);}
function shuffle<T>(items:T[],seed:number){const random=new DotNetRandom(seed);return items.map((value,index)=>({value,index,key:random.next()})).sort((a,b)=>a.key-b.key||a.index-b.index).map(x=>x.value);}
function trimDotNet(text:string){return text.replace(/^[\u0009-\u000d\u0085\p{Z}]+|[\u0009-\u000d\u0085\p{Z}]+$/gu,'');}
function words(text:string,trim=true){return text.split(' ').map(x=>trim?trimDotNet(x):x).filter(Boolean);}
export function normalizeDifficulty(value:unknown):1|3|5 {if(value===1||value==='Foundation')return 1;if(value===3||value==='Standard')return 3;if(value===5||value==='Advanced')return 5;throw new Error('Choose Foundation, Standard, or Advanced.');}
function choicesAllowed(r:ActivityRequest){return r.difficulty<5 && (r.distractorCitations??[]).some(c=>c!==r.sourceUnit.citationLabel) && (r.mode==='Simulation'?r.ruleProfile.simulationAllowMultipleChoice:r.ruleProfile.studyAllowMultipleChoice);}
export function eligibleActivities(r:ActivityRequest):ActivityType[]{if(r.knowledgeUnitKind&&r.knowledgeUnitKind!=='ExactVerseText')return [];const types:ActivityType[]=['MissingWords'];if(words(r.sourceUnit.canonicalText,false).length>=4)types.push('VerseBuilder');types.push('ReferenceMatch');if(r.mode!=='Review'&&r.nextSourceUnit&&r.nextKnowledgeUnitId)types.push('WhatComesNext');if(r.difficulty<5&&(r.mode!=='Simulation'||r.ruleProfile.simulationAllowTrueFalse&&(r.usedActivityTypes??[]).filter(t=>t==='TrueFalse').length<Math.floor(Math.max(1,r.targetCardCount??8)*(r.ruleProfile.trueFalseMaxRatio??0.1)+1e-9)))types.push('TrueFalse');return types;}
export function chooseActivity(eligible:ActivityType[],used:string[],sequence:number):ActivityType|null {if(!eligible.length)return null;if(sequence===1)return eligible.find(t=>t==='MissingWords')??eligible[0];return [...eligible].sort((a,b)=>used.filter(x=>x===a).length-used.filter(x=>x===b).length+0 || Number(used.at(-1)===a)-Number(used.at(-1)===b))[0];}
export function generateActivity(type:ActivityType,r:ActivityRequest):GeneratedActivity {
 const unit=r.sourceUnit, difficulty=r.difficulty, seed=stableSeed(unit.id,r.sessionId,r.sequence);
 const payload:Payload={citation:unit.citationLabel,prompt:'',tokens:[],difficulty};let canonicalAnswer=unit.canonicalText;let hiddenWords:string[]|undefined;let answerMode:AnswerMode='ExactText';let knowledgeUnitId=r.knowledgeUnitId;let answerSourceUnitId:string|undefined;
 switch(type){
 case 'MissingWords': {if(!trimDotNet(unit.canonicalText))throw new Error('Missing Words requires stored canonical source text.');const tokens=words(unit.canonicalText).map((text,index)=>({text,hidden:false,index}));const d=Math.max(1,Math.min(5,difficulty));const count=d===1?1:d===2?Math.max(2,Math.floor(tokens.length/6)):d===3?Math.max(3,Math.floor(tokens.length/4)):d===4?Math.max(4,Math.floor(tokens.length/2)):Math.max(1,tokens.length-1);let hideable=tokens.filter(t=>/\p{L}/u.test(t.text)&&t.text.length>2);if(!hideable.length)hideable=tokens;const indices=new Set(shuffle(hideable,seed).slice(0,count).map(t=>t.index));payload.tokens=tokens.map(t=>({...t,hidden:indices.has(t.index)}));hiddenWords=payload.tokens.filter(t=>t.hidden).map(t=>t.text);canonicalAnswer=hiddenWords.join(' ');payload.prompt=payload.tokens.map(t=>t.hidden?'____':t.text).join(' ');break;}
 case 'VerseBuilder': {const list=words(unit.canonicalText);if(list.length<4)throw new Error('Verse Builder needs a longer stored verse.');const size=difficulty<=1?Math.min(4,Math.max(2,Math.floor(list.length/2))):difficulty>=5?1:2;const chunks:string[]=[];for(let i=0;i<list.length;i+=size)chunks.push(list.slice(i,i+size).join(' '));payload.tokens=shuffle(chunks,seed).map((text,index)=>({text,index,hidden:false}));payload.prompt='Build the verse in the correct order.';answerMode='OrderedSequence';break;}
 case 'ReferenceMatch': {canonicalAnswer=unit.citationLabel;const allowed=choicesAllowed(r);const seen=new Set<string>();const choices=[unit.citationLabel,...(r.distractorCitations??[]).filter(c=>c.toLowerCase()!==unit.citationLabel.toLowerCase())].filter(c=>{const key=c.toLowerCase();if(seen.has(key))return false;seen.add(key);return true;});payload.choices=allowed&&choices.length>1?shuffle(choices.slice(0,difficulty<=1?2:4),seed):null;payload.prompt='Match the assigned Scripture to its reference.';answerMode=allowed?'SelectedChoice':'ShortFact';break;}
 case 'TrueFalse': {let statement=!r.alternateSourceUnit||seed%2===0?unit.canonicalText:r.alternateSourceUnit.canonicalText;let expected=unit.canonicalText;if(difficulty<=1){statement=words(statement,false).slice(0,4).join(' ');expected=words(expected,false).slice(0,4).join(' ');}canonicalAnswer=statement===expected?'True':'False';payload.prompt=`According to ${unit.citationLabel}, is this ${difficulty<=1?'the beginning of the stored wording':'the stored wording'}? ${statement}`;answerMode='ShortFact';break;}
 case 'WhatComesNext': {if(!r.nextSourceUnit||!r.nextKnowledgeUnitId)throw new Error('What Comes Next requires an assigned next verse.');const list=words(r.nextSourceUnit.canonicalText,false), support=r.mode!=='Simulation';canonicalAnswer=difficulty<=1&&support?list.slice(0,4).join(' '):r.nextSourceUnit.canonicalText;let instruction=difficulty<=1&&support?`Write the first ${Math.min(4,list.length)} words of the next verse.`:'Write the full next verse.';if(difficulty===3&&support&&list.length)instruction+=` It starts with: ${list[0]}`;payload.prompt=`What comes next after ${unit.citationLabel}? ${instruction}`;knowledgeUnitId=r.nextKnowledgeUnitId;answerSourceUnitId=r.nextSourceUnit.id;break;}
 default: throw new Error('Unknown activity.');
 }
 return {activityType:type,providerType:`${type}ActivityProvider`,answerMode,evaluatorVersion:EVALUATOR_VERSION,payload,answerKey:{canonicalAnswer,...(hiddenWords?{hiddenWords}:{})},sourceUnitId:unit.id,knowledgeUnitId,...(answerSourceUnitId?{answerSourceUnitId}:{})};
}
export function normalizeText(value:string|null|undefined){return Array.from(value??'').map(ch=>{const lower=ch.toLowerCase();return lower.length===ch.length?lower:ch;}).join('').replace(/[.,;:!?"'“”‘’]/g,'').replace(/[\u0009-\u000d\u0085\p{Z}]+/gu,' ').replace(/^ +| +$/g,'');}
export function evaluateAnswer(submitted:string,canonical:string){const normalizedSubmitted=normalizeText(submitted),normalizedCanonical=normalizeText(canonical),isCorrect=normalizedSubmitted===normalizedCanonical;return {isCorrect,evaluationCode:isCorrect?'ExactMatch':'Incorrect',normalizedSubmitted,normalizedCanonical,evaluatorVersion:EVALUATOR_VERSION};}
/** Optional token-ID adapter. Existing HTTP API submits joined text; identical repeated words are interchangeable there. */
export function evaluateOrderedTokens(card:GeneratedActivity,indices:number[]){const tokens=card.payload.tokens;const valid=indices.length===tokens.length&&new Set(indices).size===indices.length&&indices.every(i=>tokens.some(t=>t.index===i));const result=evaluateAnswer(indices.map(i=>tokens.find(t=>t.index===i)?.text??'').join(' '),card.answerKey.canonicalAnswer);return valid?result:{...result,isCorrect:false,evaluationCode:'Incorrect'};}
export interface MasteryScores { recognition:number;exactWording:number;reference:number;sequence:number;factualRecall:number;level:'Unseen'|'Learning'|'Review'|'Strong'|'Mastered' }
export function applyMastery(current:MasteryScores,isCorrect:boolean,hintsUsed:boolean,activityType:string,answerMode:AnswerMode='ExactText',difficulty=3):MasteryScores {const bound=(n:number)=>Math.max(0,Math.min(100,n));const next={...current,recognition:bound(current.recognition+(isCorrect?hintsUsed?4:10:-2))};const delta=isCorrect?hintsUsed?0:18:-6;if(answerMode!=='SelectedChoice'){if(activityType==='MissingWords'&&answerMode==='ExactText'){const ceiling=difficulty>=5?100:difficulty>=3?70:40;next.exactWording=isCorrect?Math.max(next.exactWording,Math.min(ceiling,bound(next.exactWording+delta))):bound(next.exactWording+delta);}else if(activityType==='ReferenceMatch')next.reference=bound(next.reference+delta);else if(activityType==='WhatComesNext'||activityType==='VerseBuilder')next.sequence=bound(next.sequence+delta);else if(activityType==='ShortAnswer')next.factualRecall=bound(next.factualRecall+delta);}next.level=next.exactWording>=80&&next.recognition>=70?'Mastered':next.exactWording>=55?'Strong':next.exactWording>0||!isCorrect&&next.recognition>0?'Review':'Learning';return next;}
export function nextReview(nowUtc:string,isCorrect:boolean){return new Date(Date.parse(nowUtc)+(isCorrect?172800000:0)).toISOString();}
export function toCardDto(card:GeneratedActivity,metadata:{id:string;sessionId:string;sequence:number;total:number},source:SourceUnit,showCitation=true,exposeDebug=false){let prompt=card.activityType==='ReferenceMatch'?source.canonicalText:card.payload.prompt;if(card.activityType==='WhatComesNext')prompt+=` ${source.canonicalText}`;if(!showCitation)prompt=prompt.replaceAll(source.citationLabel,'the assigned passage');return {...metadata,activityType:card.activityType,citation:showCitation&&card.activityType!=='ReferenceMatch'?source.citationLabel:'Assigned passage',prompt,tokens:card.payload.tokens.map(t=>({display:t.hidden?'____':t.text,hidden:t.hidden,index:t.index})),choices:card.payload.choices?.length?card.payload.choices:null,debugAnswer:exposeDebug?card.answerKey.canonicalAnswer:null};}
