import { describe, expect, it } from 'vitest';
import { generateActivity, eligibleActivities, chooseActivity, evaluateAnswer, applyMastery, normalizeText, stableSeed, DotNetRandom, evaluateOrderedTokens, toCardDto, type ActivityRequest } from './engine';
const unit = {id:'00112233-4455-6677-8899-aabbccddeeff', citationLabel:'Daniel 1:1', canonicalText:'one two three four five six seven eight nine ten eleven twelve'};
const request: ActivityRequest = {sourceUnit:unit,knowledgeUnitId:'knowledge',sessionId:'ffeeddcc-bbaa-9988-7766-554433221100',sequence:1,difficulty:3,mode:'Practice',ruleProfile:{studyAllowMultipleChoice:true,simulationAllowMultipleChoice:false,simulationAllowTrueFalse:true,trueFalseMaxRatio:0.1},nextSourceUnit:{...unit,id:'next',canonicalText:'Next stored verse has several words.'}, nextKnowledgeUnitId:'next-knowledge',distractorCitations:['Daniel 1:2','Daniel 1:3','Daniel 1:4']};
describe('C# activity parity',()=>{
 it('uses .NET seeded Random reference values',()=>{const rng=new DotNetRandom(42);expect([rng.next(),rng.next(),rng.next()]).toEqual([1434747710,302596119,269548474]);expect(stableSeed(unit.id,request.sessionId,1)).toBe(stableSeed(unit.id,request.sessionId,1));});
 it.each([1,3,5])('preserves difficulty %i and canonical answers', difficulty=>{
 const r={...request,difficulty};
 for(const type of ['MissingWords','VerseBuilder','ReferenceMatch','WhatComesNext','TrueFalse'] as const){const card=generateActivity(type,r);expect(card).toEqual(generateActivity(type,r));expect(card.payload.difficulty).toBe(difficulty);expect(evaluateAnswer(card.answerKey.canonicalAnswer,card.answerKey.canonicalAnswer).isCorrect).toBe(true);}
 expect(generateActivity('MissingWords',r).answerKey.hiddenWords).toHaveLength(difficulty===1?1:difficulty===3?3:11);
 expect(generateActivity('VerseBuilder',r).payload.tokens).toHaveLength(difficulty===1?3:difficulty===3?6:12);
 expect(generateActivity('ReferenceMatch',r).payload.choices?.length??0).toBe(difficulty===1?2:difficulty===3?4:0);
 });
 it('excludes advanced true false and review next verse; caps simulation true false',()=>{expect(eligibleActivities({...request,difficulty:5})).not.toContain('TrueFalse');expect(eligibleActivities({...request,mode:'Review'})).not.toContain('WhatComesNext');expect(eligibleActivities({...request,mode:'Simulation',targetCardCount:10,usedActivityTypes:['TrueFalse']})).not.toContain('TrueFalse');expect(chooseActivity(['VerseBuilder','MissingWords'],[],1)).toBe('MissingWords');});
 it('credits next verse and hides reference answer metadata',()=>{const card=generateActivity('WhatComesNext',{...request,difficulty:1});expect(card.knowledgeUnitId).toBe('next-knowledge');expect(card.answerKey.canonicalAnswer).toBe('Next stored verse has');expect(generateActivity('WhatComesNext',{...request,difficulty:1,mode:'Simulation'}).answerKey.canonicalAnswer).toBe(request.nextSourceUnit!.canonicalText);expect(toCardDto(generateActivity('ReferenceMatch',request),{id:'card',sessionId:request.sessionId,sequence:1,total:8},unit).citation).toBe('Assigned passage');});
 it('retains duplicate word identity and rejects missing, repeated and reversed answers',()=>{const card=generateActivity('VerseBuilder',{...request,difficulty:5,sourceUnit:{...unit,canonicalText:'one two one three'}});const tokens=card.payload.tokens;const used=new Set<number>();const order=['one','two','one','three'].map(word=>{const t=tokens.find(t=>t.text===word&&!used.has(t.index))!;used.add(t.index);return t.index;});expect(evaluateOrderedTokens(card,order).isCorrect).toBe(true);expect(evaluateOrderedTokens(card,[...order].reverse()).isCorrect).toBe(false);expect(evaluateOrderedTokens(card,order.slice(1)).isCorrect).toBe(false);expect(evaluateOrderedTokens(card,[order[0],order[0],...order.slice(2)]).isCorrect).toBe(false);});
 it('normalizes configured punctuation only and preserves word order',()=>{expect(normalizeText(' “Defile”  Himself. ')).toBe('defile himself');expect(evaluateAnswer('himself defile','defile himself').isCorrect).toBe(false);expect(normalizeText('well-being / yes')).toBe('well-being / yes');});
 it('awards skill evidence only and applies difficulty ceilings',()=>{const zero={recognition:0,exactWording:0,reference:0,sequence:0,factualRecall:0,level:'Unseen' as const};expect(applyMastery(zero,true,false,'VerseBuilder','OrderedSequence',3).sequence).toBe(18);expect(applyMastery(zero,true,false,'ReferenceMatch','SelectedChoice',3).reference).toBe(0);expect(applyMastery({...zero,exactWording:39},true,false,'MissingWords','ExactText',1).exactWording).toBe(40);expect(applyMastery({...zero,exactWording:90},true,false,'MissingWords','ExactText',1).exactWording).toBe(90);});
});

it('matches cards generated by the actual net10.0 domain assembly',async()=>{
 const fixture=(await import('./engine-csharp-fixtures.json')).default;
 expect(stableSeed(unit.id,request.sessionId,1)).toBe(fixture.seed);
 for(const reference of fixture.cards){
  const generated=generateActivity(reference.type as Parameters<typeof generateActivity>[0],{...request,difficulty:reference.difficulty});
  const p=reference.payload;
  expect(generated.payload).toMatchObject({citation:p.Citation,prompt:p.Prompt,difficulty:p.Difficulty,tokens:p.Tokens.map(t=>({text:t.Text,hidden:t.Hidden,index:t.Index}))});
  expect(generated.payload.choices??null).toEqual('Choices' in p?p.Choices:null);
  expect(generated.answerKey.canonicalAnswer).toBe(reference.answerKey.CanonicalAnswer);
 }
});

it('uses .NET whitespace rather than JavaScript BOM whitespace',()=>{expect(normalizeText('\u0085ONE\u0085TWO\u0085')).toBe('one two');expect(normalizeText('\uFEFFone')).toBe('\uFEFFone');expect(normalizeText('İ')).toBe('İ');});

it('keeps BOM tokens solvable and trims .NET next-line whitespace',()=>{
 const card=generateActivity('VerseBuilder',{...request,difficulty:5,sourceUnit:{...unit,canonicalText:'one two \uFEFFthree four'}});
 expect(card.payload.tokens.some(t=>t.text==='\uFEFFthree')).toBe(true);
 const correct=['one','two','\uFEFFthree','four'].map(word=>card.payload.tokens.find(t=>t.text===word)!.index);
 expect(evaluateOrderedTokens(card,correct).isCorrect).toBe(true);
 const nextLine=generateActivity('VerseBuilder',{...request,difficulty:5,sourceUnit:{...unit,canonicalText:'one two \u0085three four'}});
 expect(nextLine.payload.tokens.some(t=>t.text==='three')).toBe(true);
});
