import {chapterBoundedPage} from './chapter-bounded-page';
import type {RequestContext} from '../types';
import type {ChapterGroup} from './chapter-groups';
export type GroupMetadata=Omit<ChapterGroup,'sourceUnitIds'>&{assignedPassages:number;sortKey:string};
interface OwnedGeneration {seasonId:string;workId:string}
const args=(ctx:RequestContext,w:OwnedGeneration)=>[ctx.orgId,w.seasonId,ctx.actor.userId,w.workId];
/** Window calculations inspect only the capped, immutable source metadata; callers materialize one page. */
export function chapterGroupCtes(){return `sourceRows AS (
 SELECT json_extract(e.value,'$.id') AS id,json_extract(e.value,'$.parentKey') AS parentKey,json_extract(e.value,'$.contentPackId') AS packId,json_extract(e.value,'$.bookKey') AS bookKey,json_extract(e.value,'$.chapter') AS chapter,json_extract(e.value,'$.verse') AS verse,json_extract(e.value,'$.ordinal') AS ordinal
 FROM Records m INDEXED BY Records_training_scope JOIN json_each(m.data,'$.entries') e WHERE m.org_id=? AND m.season_id=? AND m.owner_id=? AND m.kind='pbe-chapter-manifest' AND json_extract(m.data,'$.generationId')=? AND json_extract(m.data,'$.family')='sources'),
 numbered AS (SELECT *,verse-row_number() OVER(PARTITION BY parentKey ORDER BY verse,id) AS run FROM sourceRows WHERE chapter IS NOT NULL),
 runs AS (SELECT *,count(*) OVER(PARTITION BY parentKey,run) AS n,row_number() OVER(PARTITION BY parentKey,run ORDER BY verse,id) AS pos FROM numbered),
 lengths AS (SELECT *,((n+4)/5) AS k FROM runs),
 sizes AS (SELECT *,n/k AS base,n%k AS extra FROM lengths),
 balanced AS (SELECT *,CASE WHEN pos<=(base+1)*extra THEN (pos-1)/(base+1) ELSE extra+(pos-1-(base+1)*extra)/base END AS groupNo FROM sizes),
 boundaries AS (SELECT *,first_value(id) OVER(PARTITION BY parentKey,run,groupNo ORDER BY verse,id) AS firstId,first_value(id) OVER(PARTITION BY parentKey,run,groupNo ORDER BY verse DESC,id DESC) AS lastId FROM balanced),
 members AS (SELECT id,parentKey,'group:'||parentKey||':'||firstId||':'||lastId AS groupKey FROM boundaries UNION ALL SELECT id,parentKey,null AS groupKey FROM sourceRows WHERE chapter IS NULL)`;}
export async function chapterGroupPage(ctx:RequestContext,w:OwnedGeneration,after:string){
 const rows=await chapterBoundedPage<{key:string;parentChapterKey:string|null;kind:GroupMetadata['kind'];packId:string;bookKey:string;chapter:number|null;assignedPassages:number;firstVerse:number;lastVerse:number;sortKey:string}>(ctx,`WITH ${chapterGroupCtes()}, groups AS (
 SELECT parentKey AS key,null AS parentChapterKey,CASE WHEN chapter IS NULL THEN 'Introduction' ELSE 'Chapter' END AS kind,packId,bookKey,chapter,count(*) AS assignedPassages,0 AS firstVerse,0 AS lastVerse FROM sourceRows GROUP BY parentKey
 UNION ALL SELECT m.groupKey,m.parentKey,'PassageGroup',s.packId,s.bookKey,s.chapter,count(*),min(s.verse),max(s.verse) FROM members m JOIN sourceRows s ON s.id=m.id WHERE m.groupKey IS NOT NULL GROUP BY m.groupKey),
 ordered AS (SELECT *,bookKey||':'||printf('%08d',coalesce(chapter,99999999))||':'||packId||':'||printf('%08d',firstVerse)||':'||key AS sortKey FROM groups)
 SELECT sortKey AS key,json_object('key',key,'parentChapterKey',parentChapterKey,'kind',kind,'packId',packId,'bookKey',bookKey,'chapter',chapter,'assignedPassages',assignedPassages,'firstVerse',firstVerse,'lastVerse',lastVerse,'sortKey',sortKey) AS payload FROM ordered WHERE sortKey>? ORDER BY sortKey LIMIT 128`,[...args(ctx,w),after]);
 return rows.map(r=>({key:r.key,parentChapterKey:r.parentChapterKey,kind:r.kind,contentPackId:r.packId,bookKey:r.bookKey,chapter:r.chapter,wholeChapterAssigned:r.kind==='Chapter'?false:null,assignedPassages:r.assignedPassages,sortKey:r.sortKey,label:r.kind==='Introduction'?`${r.bookKey} introduction`:r.kind==='Chapter'?`${r.bookKey} ${r.chapter}`:`${r.bookKey} ${r.chapter}:${r.firstVerse}${r.firstVerse===r.lastVerse?'':`–${r.lastVerse}`}`,scopeLabel:r.kind==='Introduction'?`${r.assignedPassages} assigned introduction units`:`${r.assignedPassages} assigned verses`}) satisfies GroupMetadata);
}
export async function savedGroup(ctx:RequestContext,w:OwnedGeneration,after:string){
 const row=await ctx.env.DB.prepare("SELECT e.value FROM Records m INDEXED BY Records_training_scope JOIN json_each(m.data,'$.entries') e WHERE m.org_id=? AND m.season_id=? AND m.owner_id=? AND m.kind='pbe-chapter-manifest' AND json_extract(m.data,'$.generationId')=? AND json_extract(m.data,'$.family')='groups' AND json_extract(e.value,'$.sortKey')>? ORDER BY json_extract(e.value,'$.sortKey') LIMIT 1").bind(...args(ctx,w),after).first<{value:string}>();return row?JSON.parse(row.value) as GroupMetadata:null;
}
export async function groupCoveredPassages(ctx:RequestContext,w:OwnedGeneration,key:string){
 const row=await ctx.env.DB.prepare(`WITH ${chapterGroupCtes()}, selected AS (SELECT id FROM members WHERE parentKey=? OR groupKey=?)
 SELECT count(DISTINCT unit.value) AS n FROM Records h INDEXED BY Records_training_scope JOIN json_each(h.data,'$.entries') e JOIN json_each(e.value,'$.question.sourceUnitIds') unit WHERE h.org_id=? AND h.season_id=? AND h.owner_id=? AND h.kind='pbe-chapter-manifest' AND json_extract(h.data,'$.generationId')=? AND json_extract(h.data,'$.family')='heads' AND unit.value IN (SELECT id FROM selected)`).bind(...args(ctx,w),key,key,...args(ctx,w)).first<{n:number}>();return row?.n??0;
}
export async function groupTargetPage(ctx:RequestContext,w:OwnedGeneration,key:string,after:string){
 return chapterBoundedPage<{id:string;skill:'FactualRecall'|'ExactWords';sourceUnitIds:string[]}>(ctx,`WITH ${chapterGroupCtes()}, selected AS (SELECT id FROM members WHERE parentKey=? OR groupKey=?)
 SELECT json_extract(e.value,'$.target.id') AS key,json_extract(e.value,'$.target') AS payload FROM Records m INDEXED BY Records_training_scope JOIN json_each(m.data,'$.entries') e WHERE m.org_id=? AND m.season_id=? AND m.owner_id=? AND m.kind='pbe-chapter-manifest' AND json_extract(m.data,'$.generationId')=? AND json_extract(m.data,'$.family')='targets' AND json_extract(e.value,'$.target.id')>? AND EXISTS(SELECT 1 FROM json_each(e.value,'$.target.sourceUnitIds') unit WHERE unit.value IN (SELECT id FROM selected)) ORDER BY json_extract(e.value,'$.target.id') LIMIT 128`,[...args(ctx,w),key,key,...args(ctx,w),after]);
}
export async function targetVariantCounts(ctx:RequestContext,w:OwnedGeneration,targets:{id:string;skill:string}[]){
 // Materialize the compact head parts once; otherwise the LEFT JOIN reparses every manifest for each target.
 const rows=await ctx.env.DB.prepare("WITH headParts AS MATERIALIZED (SELECT json_extract(e.value,'$.question.id') AS questionId,json_extract(e.value,'$.question.kind') AS kind,json_extract(p.value,'$.targetId') AS targetId FROM Records m INDEXED BY Records_training_scope JOIN json_each(m.data,'$.entries') e JOIN json_each(e.value,'$.question.parts') p WHERE m.org_id=? AND m.season_id=? AND m.owner_id=? AND m.kind='pbe-chapter-manifest' AND json_extract(m.data,'$.generationId')=? AND json_extract(m.data,'$.family')='heads') SELECT json_extract(t.value,'$.id') AS targetId,count(DISTINCT h.questionId) AS n FROM json_each(?) t LEFT JOIN headParts h ON h.targetId=json_extract(t.value,'$.id') AND h.kind<>'TrueFalse' AND (json_extract(t.value,'$.skill')<>'ExactWords' OR h.kind='ExactWords') GROUP BY json_extract(t.value,'$.id')").bind(...args(ctx,w),JSON.stringify(targets.map(t=>({id:t.id,skill:t.skill})))).all<{targetId:string;n:number}>();return new Map(rows.results.map(r=>[r.targetId,r.n]));
}
export async function savedTargetIds(ctx:RequestContext,w:OwnedGeneration,after:string){return (await ctx.env.DB.prepare("SELECT json_extract(e.value,'$.target.id') AS id FROM Records m INDEXED BY Records_training_scope JOIN json_each(m.data,'$.entries') e WHERE m.org_id=? AND m.season_id=? AND m.owner_id=? AND m.kind='pbe-chapter-manifest' AND json_extract(m.data,'$.generationId')=? AND json_extract(m.data,'$.family')='targets' AND json_extract(e.value,'$.target.id')>? ORDER BY json_extract(e.value,'$.target.id') LIMIT 128").bind(...args(ctx,w),after).all<{id:string}>()).results.map(r=>r.id);}
export async function savedRetentions<T>(ctx:RequestContext,w:OwnedGeneration,ids:string[]):Promise<T[]>{return chapterBoundedPage<T>(ctx,"SELECT json_extract(e.value,'$.targetId') AS key,e.value AS payload FROM Records m INDEXED BY Records_training_scope JOIN json_each(m.data,'$.entries') e WHERE m.org_id=? AND m.season_id=? AND m.owner_id=? AND m.kind='pbe-chapter-manifest' AND json_extract(m.data,'$.generationId')=? AND json_extract(m.data,'$.family')='retentions' AND json_extract(e.value,'$.targetId') IN (SELECT value FROM json_each(?)) ORDER BY key LIMIT 128",[...args(ctx,w),JSON.stringify(ids)]);}
