import type {VerifiedCooperationScope} from './cooperation-capability';
import {currentCooperationSourcesSql} from './cooperation-inputs';
import {entriesSql,type CooperationWork} from './cooperation-storage';
import {builtInContentSql} from '../application/library-access';
export type CooperationGuardInputs=Pick<CooperationWork,'workId'|'seasonId'|'pageCount'|'roster'|'descriptors'|'baseGuards'>;
/** One whole-cohort predicate checks exact sets, phantoms, pointer absences and captured availability. */
export function cooperationInputGuard(scope:VerifiedCooperationScope,w:CooperationGuardInputs,readOnly=false){
 const {ctx}=scope,id=crypto.randomUUID();
 const sql=`WITH root(org,season,generation,roster,descriptors,baseGuards,pageCount) AS (VALUES(?,?,?,?,?,?,?)),
 currentRoster AS (SELECT u.id AS studentId,u.display_name AS displayName,m.revision AS membershipRevision FROM root r JOIN Users u ON u.org_id=r.org AND u.active=1 AND u.kind='Student' AND u.role='Student' JOIN Records m ON m.kind='membership' AND m.org_id=r.org AND m.season_id=r.season AND m.owner_id=u.id AND m.id=r.season||':'||u.id),
 context AS (SELECT r.org,r.season,c.studentId AS student FROM root r CROSS JOIN currentRoster c),meta AS (SELECT generation FROM root),
 sourceInputs AS (${entriesSql('sources')}),assignmentInputs AS (${entriesSql('assignments')}),rawGuardInputs AS (${entriesSql('guards')}),d1Inputs AS (${entriesSql('d1guards')}),
 currentSources AS MATERIALIZED (${currentCooperationSourcesSql}),
 limits AS MATERIALIZED (SELECT (SELECT count(*) FROM (SELECT sourceKind,contentPackId,sourceUnitId FROM currentSources GROUP BY sourceKind,contentPackId,sourceUnitId LIMIT 10001))<=10000 AND (SELECT count(*) FROM (SELECT studentId,sourceKind,contentPackId,sourceUnitId FROM currentSources GROUP BY studentId,sourceKind,contentPackId,sourceUnitId LIMIT 50001))<=50000 AND NOT EXISTS(SELECT a.kind FROM context c JOIN Records a ON a.org_id=c.org AND a.season_id=c.season AND a.owner_id=c.student AND a.kind IN ('assignment','pbe-introduction-assignment') GROUP BY a.kind HAVING count(*)>10000) AS ok),
 currentBank AS MATERIALIZED (SELECT c.student,r.kind,r.id,r.revision FROM context c JOIN Records r INDEXED BY Records_training_scope ON r.org_id=c.org AND r.season_id=c.season AND r.kind IN ('pbe-target','pbe-question-head') AND r.owner_id IN (SELECT s.sourceUnitId FROM currentSources s WHERE s.studentId=c.student)),
 allGuards AS (SELECT g.value FROM root r JOIN json_each(r.baseGuards) g UNION ALL SELECT value FROM rawGuardInputs UNION ALL SELECT value FROM assignmentInputs UNION ALL SELECT json_extract(value,'$.introductionGuard') FROM assignmentInputs WHERE json_type(value,'$.introductionGuard')='object' UNION ALL SELECT g.value FROM sourceInputs s JOIN json_each(s.value,'$.guards') g),
 d1Flat AS (SELECT json_extract(value,'$.studentId') AS studentId,json_extract(value,'$.family') AS family,json_extract(value,'$.value') AS value FROM d1Inputs),
 d1Guards AS (SELECT studentId,value FROM d1Flat WHERE family<>'sources' UNION ALL SELECT studentId,json_extract(value,'$.introductionGuard') FROM d1Flat WHERE family='guards' AND json_type(value,'$.introductionGuard')='object' UNION ALL SELECT f.studentId,g.value FROM d1Flat f JOIN json_each(f.value,'$.guards') g WHERE f.family='sources'),
 d1Current AS MATERIALIZED (SELECT json_extract(d.value,'$.studentId') AS studentId,
 json_extract(d.value,'$.scopeVersion') IS NOT NULL
 AND NOT EXISTS(SELECT 1 FROM d1Guards g WHERE g.studentId=json_extract(d.value,'$.studentId') AND CASE WHEN json_extract(g.value,'$.kind') LIKE '@active-%' THEN NOT EXISTS(SELECT 1 FROM currentRoster WHERE studentId=g.studentId)
 WHEN json_extract(g.value,'$.revision') IS NULL THEN EXISTS(SELECT 1 FROM Records r WHERE r.org_id=root.org AND r.kind=json_extract(g.value,'$.kind') AND r.id=json_extract(g.value,'$.id'))
 ELSE NOT EXISTS(SELECT 1 FROM Records r WHERE (r.org_id=root.org OR ${builtInContentSql('r')}) AND r.kind=json_extract(g.value,'$.kind') AND r.id=json_extract(g.value,'$.id') AND r.revision=json_extract(g.value,'$.revision')) END)
 AND NOT EXISTS(SELECT sourceUnitId FROM currentSources WHERE studentId=json_extract(d.value,'$.studentId') EXCEPT SELECT json_extract(value,'$.id') FROM d1Flat WHERE studentId=json_extract(d.value,'$.studentId') AND family='sources')
 AND NOT EXISTS(SELECT json_extract(value,'$.id') FROM d1Flat WHERE studentId=json_extract(d.value,'$.studentId') AND family='sources' EXCEPT SELECT sourceUnitId FROM currentSources WHERE studentId=json_extract(d.value,'$.studentId'))
 AND (SELECT count(*) FROM Records a WHERE a.org_id=root.org AND a.season_id=root.season AND a.owner_id=json_extract(d.value,'$.studentId') AND a.kind IN ('assignment','pbe-introduction-assignment'))=(SELECT count(*) FROM d1Flat WHERE studentId=json_extract(d.value,'$.studentId') AND family='guards' AND json_extract(value,'$.kind') IN ('assignment','pbe-introduction-assignment'))
 AND (SELECT count(*) FROM currentBank WHERE student=json_extract(d.value,'$.studentId') AND kind='pbe-target')=(SELECT count(*) FROM d1Flat WHERE studentId=json_extract(d.value,'$.studentId') AND family='targets')
 AND (SELECT count(*) FROM currentBank WHERE student=json_extract(d.value,'$.studentId') AND kind='pbe-question-head')=(SELECT count(*) FROM d1Flat WHERE studentId=json_extract(d.value,'$.studentId') AND family='heads')
 AND (SELECT count(*) FROM Records m WHERE m.kind='pbe-chapter-manifest' AND m.org_id=root.org AND m.season_id=root.season AND m.owner_id=json_extract(d.value,'$.studentId') AND json_extract(m.data,'$.generationId')=json_extract(d.value,'$.generationId'))=json_extract(d.value,'$.pageCount') AS valid
 FROM root JOIN json_each(root.descriptors) d WHERE json_extract(d.value,'$.complete')=1),
 dirtyValid AS MATERIALIZED (SELECT json_extract(d.value,'$.studentId') AS studentId,NOT EXISTS(SELECT 1 FROM Records dirty WHERE dirty.kind='pbe-evidence-dirty' AND dirty.org_id=root.org AND dirty.season_id=root.season AND dirty.owner_id=json_extract(d.value,'$.studentId') AND coalesce(json_extract(dirty.data,'$.generation'),0)<>coalesce(json_extract(dirty.data,'$.completedGeneration'),0) AND dirty.id IN (SELECT student||':'||root.season||':'||id FROM currentBank WHERE student=json_extract(d.value,'$.studentId') AND kind='pbe-target')) AS valid FROM root JOIN json_each(root.descriptors) d),d1Valid AS MATERIALIZED (SELECT c.studentId,c.valid AND d.valid AS valid FROM d1Current c JOIN dirtyValid d ON d.studentId=c.studentId),
 valid AS (SELECT
 (SELECT ok FROM limits) AND NOT EXISTS(SELECT 1 FROM Records m WHERE m.kind='pbe-cooperation-manifest' AND m.org_id=root.org AND m.season_id=root.season AND m.owner_id IS NULL AND json_extract(m.data,'$.generationId')=root.generation AND m.revision<>1) AND (SELECT count(*) FROM Records m WHERE m.kind='pbe-cooperation-manifest' AND m.org_id=root.org AND m.season_id=root.season AND m.owner_id IS NULL AND json_extract(m.data,'$.generationId')=root.generation)=root.pageCount
 AND NOT EXISTS(SELECT studentId,displayName,membershipRevision FROM currentRoster EXCEPT SELECT json_extract(value,'$.studentId'),json_extract(value,'$.displayName'),json_extract(value,'$.membershipRevision') FROM json_each(root.roster))
 AND NOT EXISTS(SELECT json_extract(value,'$.studentId'),json_extract(value,'$.displayName'),json_extract(value,'$.membershipRevision') FROM json_each(root.roster) EXCEPT SELECT studentId,displayName,membershipRevision FROM currentRoster)
 AND NOT EXISTS(SELECT 1 FROM allGuards g WHERE CASE WHEN json_extract(g.value,'$.revision') IS NULL THEN EXISTS(SELECT 1 FROM Records r WHERE r.org_id=root.org AND r.kind=json_extract(g.value,'$.kind') AND r.id=json_extract(g.value,'$.id')) ELSE NOT EXISTS(SELECT 1 FROM Records r WHERE (r.org_id=root.org OR ${builtInContentSql('r')}) AND r.kind=json_extract(g.value,'$.kind') AND r.id=json_extract(g.value,'$.id') AND r.revision=json_extract(g.value,'$.revision')) END)
 AND NOT EXISTS(SELECT studentId,sourceKind,contentPackId,sourceUnitId FROM currentSources EXCEPT SELECT json_extract(value,'$.studentId'),json_extract(value,'$.sourceKind'),json_extract(value,'$.contentPackId'),json_extract(value,'$.sourceUnitId') FROM sourceInputs)
 AND NOT EXISTS(SELECT json_extract(value,'$.studentId'),json_extract(value,'$.sourceKind'),json_extract(value,'$.contentPackId'),json_extract(value,'$.sourceUnitId') FROM sourceInputs EXCEPT SELECT studentId,sourceKind,contentPackId,sourceUnitId FROM currentSources)
 AND NOT EXISTS(SELECT 1 FROM context c WHERE (SELECT count(*) FROM Records a WHERE a.org_id=c.org AND a.season_id=c.season AND a.owner_id=c.student AND a.kind IN ('assignment','pbe-introduction-assignment'))<>(SELECT count(*) FROM assignmentInputs WHERE json_extract(value,'$.studentId')=c.student))
 AND NOT EXISTS(SELECT student,kind,id FROM currentBank EXCEPT SELECT json_extract(value,'$.studentId'),json_extract(value,'$.kind'),json_extract(value,'$.id') FROM rawGuardInputs WHERE json_extract(value,'$.kind') IN ('pbe-target','pbe-question-head'))
 AND NOT EXISTS(SELECT json_extract(value,'$.studentId'),json_extract(value,'$.kind'),json_extract(value,'$.id') FROM rawGuardInputs WHERE json_extract(value,'$.kind') IN ('pbe-target','pbe-question-head') EXCEPT SELECT student,kind,id FROM currentBank)
 AND NOT EXISTS(SELECT 1 FROM json_each(root.descriptors) d WHERE CASE WHEN json_extract(d.value,'$.pointerRevision') IS NULL THEN EXISTS(SELECT 1 FROM Records p WHERE p.kind='pbe-chapter-work' AND p.org_id=root.org AND p.id=json_extract(d.value,'$.studentId')||':'||root.season) ELSE NOT EXISTS(SELECT 1 FROM Records p WHERE p.kind='pbe-chapter-work' AND p.org_id=root.org AND p.season_id=root.season AND p.owner_id=json_extract(d.value,'$.studentId') AND p.id=p.owner_id||':'||root.season AND p.revision=json_extract(d.value,'$.pointerRevision')) END)
 AND NOT EXISTS(SELECT 1 FROM json_each(root.descriptors) d JOIN d1Valid v ON v.studentId=json_extract(d.value,'$.studentId') WHERE json_extract(d.value,'$.availability')<>'Unassigned' AND v.valid<>(json_extract(d.value,'$.availability')='Known')) AS ok FROM root)
 ${readOnly?'SELECT ok AS valid FROM valid':"INSERT INTO Records(kind,id,org_id,data) SELECT 'audit',?,?,CASE WHEN ok THEN ? ELSE 'invalid-json' END FROM valid"}`;
 return ctx.env.DB.prepare(sql).bind(ctx.orgId,w.seasonId,w.workId,JSON.stringify(w.roster),JSON.stringify(w.descriptors),JSON.stringify(w.baseGuards),w.pageCount,...(readOnly?[]:[id,ctx.orgId,JSON.stringify({id,action:'pbe.cooperation.inputs'})]));
}
