import {chapterSourcePredicates} from './chapter-source-pages';
import {chapterInputGuard} from './chapter-manifest';
import {cooperationPage,cooperationPageBudget,cooperationTooLarge,entriesSql,type AssignedSource,type CooperationWork,type GuardEntry,type SubjectDescriptor} from './cooperation-storage';
import type {VerifiedCooperationScope} from './cooperation-capability';
const {scriptureFrom,personallyAssigned,introductionFrom}=chapterSourcePredicates;
export const sourceIdentitySql=(kind:string,pack:string,id:string)=>`json_array(${kind},${pack},${id})`;
/** Metadata only: the shared source predicates never select canonicalText here. */
export const currentCooperationSourcesSql=`SELECT c.student AS studentId,CASE WHEN json_extract(p.data,'$.sourceType')='Scripture' THEN 'Scripture' ELSE 'Commentary' END AS sourceKind,json_extract(u.data,'$.contentPackId') AS contentPackId,json_extract(u.data,'$.id') AS sourceUnitId,json_array(json_object('kind','source','id',u.id,'revision',u.revision),json_object('kind','pack','id',p.id,'revision',p.revision)) AS guards ${scriptureFrom} ${personallyAssigned}
 UNION SELECT c.student,'Commentary',intro.id,json_extract(unit.value,'$.id'),json_array(json_object('kind','pbe-introduction','id',intro.id,'revision',intro.revision)) ${introductionFrom}`;
const personalContext='context(org,season,student) AS (VALUES(?,?,?))';
function args(scope:VerifiedCooperationScope,w:CooperationWork){const student=w.roster[w.subjectIndex].studentId;scope.assertSubject(student,w.roster);return [scope.ctx.orgId,w.seasonId,student];}
export async function cooperationCaps(scope:VerifiedCooperationScope,roster:CooperationWork['roster']){
 const {ctx,seasonId}=scope;
 const result=await ctx.env.DB.prepare(`WITH context AS (SELECT ? AS org,? AS season,value AS student FROM json_each(?)),sources AS (${currentCooperationSourcesSql})
 SELECT (SELECT count(*) FROM (SELECT sourceKind,contentPackId,sourceUnitId FROM sources GROUP BY sourceKind,contentPackId,sourceUnitId LIMIT 10001)) AS sources,(SELECT count(*) FROM (SELECT studentId,sourceKind,contentPackId,sourceUnitId FROM sources GROUP BY studentId,sourceKind,contentPackId,sourceUnitId LIMIT 50001)) AS pairs,
 (SELECT count(*) FROM (SELECT a.id FROM context c JOIN Records a ON a.org_id=c.org AND a.season_id=c.season AND a.owner_id=c.student AND a.kind='assignment' LIMIT 10001)) AS assignments,
 (SELECT count(*) FROM (SELECT a.id FROM context c JOIN Records a ON a.org_id=c.org AND a.season_id=c.season AND a.owner_id=c.student AND a.kind='pbe-introduction-assignment' LIMIT 10001)) AS intros`).bind(ctx.orgId,seasonId,JSON.stringify(roster.map(r=>r.studentId))).first<{sources:number;pairs:number;assignments:number;intros:number}>();
 if(result!.sources>10000||result!.pairs>50000||result!.assignments>10000||result!.intros>10000)throw cooperationTooLarge();
}
export async function captureSubjectSources(scope:VerifiedCooperationScope,w:CooperationWork){
 return cooperationPage<AssignedSource>(scope.ctx,`WITH ${personalContext},sources AS (${currentCooperationSourcesSql}) SELECT json_array(sourceKind,contentPackId,sourceUnitId) AS key,json_object('studentId',studentId,'sourceKind',sourceKind,'contentPackId',contentPackId,'sourceUnitId',sourceUnitId,'guards',json(guards)) AS payload FROM sources WHERE json_array(sourceKind,contentPackId,sourceUnitId)>? ORDER BY key LIMIT 128`,[...args(scope,w),w.after],cooperationPageBudget(w));
}
export async function captureSubjectAssignments(scope:VerifiedCooperationScope,w:CooperationWork){
 return cooperationPage<GuardEntry&{introductionGuard:GuardEntry|null}>(scope.ctx,`WITH ${personalContext} SELECT a.kind||':'||a.id AS key,json_object('studentId',c.student,'kind',a.kind,'id',a.id,'revision',a.revision,'introductionGuard',CASE WHEN a.kind='pbe-introduction-assignment' THEN json_object('studentId',c.student,'kind','pbe-introduction','id',json_extract(a.data,'$.contentPackId'),'revision',intro.revision) END) AS payload FROM context c JOIN Records a INDEXED BY Records_training_scope ON a.org_id=c.org AND a.season_id=c.season AND a.owner_id=c.student AND a.kind IN ('assignment','pbe-introduction-assignment') LEFT JOIN Records intro ON intro.kind='pbe-introduction' AND intro.org_id=c.org AND intro.id=json_extract(a.data,'$.contentPackId') WHERE a.kind||':'||a.id>? ORDER BY key LIMIT 128`,[...args(scope,w),w.after],cooperationPageBudget(w));
}
export async function captureSubjectGeneration(scope:VerifiedCooperationScope,w:CooperationWork):Promise<SubjectDescriptor>{
 const [org,season,student]=args(scope,w),ctx=scope.ctx;
 const pointer=await ctx.env.DB.prepare("SELECT revision,json_extract(data,'$.workId') AS generationId,json_extract(data,'$.scopeVersion') AS scopeVersion,json_extract(data,'$.stage') AS stage,json_extract(data,'$.reason') AS reason,json_extract(data,'$.pageCount') AS pageCount FROM Records WHERE org_id=? AND kind='pbe-chapter-work' AND id=? AND season_id=? AND owner_id=?").bind(org,`${student}:${season}`,season,student).first<{revision:number;generationId:string;scopeVersion:string|null;stage:string;reason:string|null;pageCount:number}>();
 const count=await ctx.env.DB.prepare("SELECT count(*) AS n FROM Records m JOIN json_each(m.data,'$.entries') e WHERE m.kind='pbe-cooperation-manifest' AND m.org_id=? AND m.season_id=? AND m.owner_id IS NULL AND json_extract(m.data,'$.generationId')=? AND json_extract(m.data,'$.family')='sources' AND json_extract(e.value,'$.studentId')=?").bind(org,season,w.workId,student).first<{n:number}>();
 const complete=pointer?.stage==='Complete';
 const dirty=await ctx.env.DB.prepare("SELECT count(*) AS n FROM Records d WHERE d.kind='pbe-evidence-dirty' AND d.org_id=? AND d.season_id=? AND d.owner_id=? AND coalesce(json_extract(d.data,'$.generation'),0)<>coalesce(json_extract(d.data,'$.completedGeneration'),0) AND d.id IN (SELECT ?||':'||?||':'||t.id FROM Records t WHERE t.kind='pbe-target' AND t.org_id=? AND t.season_id=? AND t.owner_id IN (SELECT json_extract(e.value,'$.sourceUnitId') FROM Records m JOIN json_each(m.data,'$.entries') e WHERE m.kind='pbe-cooperation-manifest' AND m.org_id=? AND m.season_id=? AND json_extract(m.data,'$.generationId')=? AND json_extract(m.data,'$.family')='sources' AND json_extract(e.value,'$.studentId')=?))").bind(org,season,student,student,season,org,season,org,season,w.workId,student).first<{n:number}>();
 const valid=complete&&pointer?.scopeVersion&&!dirty?.n?!!(await chapterInputGuard(ctx,season,pointer.generationId,pointer.pageCount,'evidence',true,student).first<{valid:number}>())?.valid:false;
 return {studentId:student,generationId:pointer?.generationId??null,scopeVersion:pointer?.scopeVersion??null,pointerRevision:pointer?.revision??null,pageCount:pointer?.pageCount??0,complete,availability:!count?.n?'Unassigned':valid?'Known':'Unknown',reason:!count?.n||valid?null:!pointer?'NotStarted':pointer.reason?'Blocked':complete?'DataGap':'Working'};
}
/** Every raw bank/projection expectation is captured even for an unavailable owner. */
export async function captureSubjectCurrentGuards(scope:VerifiedCooperationScope,w:CooperationWork){
 const bound=args(scope,w);
 return cooperationPage<GuardEntry>(scope.ctx,`WITH ${personalContext},meta(generation) AS (VALUES(?)),savedSources AS (${entriesSql('sources')}),ids AS (SELECT json_extract(value,'$.sourceUnitId') AS id FROM savedSources WHERE json_extract(value,'$.studentId')=(SELECT student FROM context)),bank AS (SELECT r.kind,r.id,r.revision FROM context c JOIN Records r INDEXED BY Records_training_scope ON r.org_id=c.org AND r.season_id=c.season AND r.owner_id IN (SELECT id FROM ids) AND r.kind IN ('pbe-target','pbe-question-head')),guards AS (SELECT * FROM bank UNION ALL SELECT 'pbe-target-review',c.student||':'||c.season||':'||t.id,p.revision FROM bank t CROSS JOIN context c LEFT JOIN Records p ON p.kind='pbe-target-review' AND p.org_id=c.org AND p.id=c.student||':'||c.season||':'||t.id WHERE t.kind='pbe-target' UNION ALL SELECT 'pbe-evidence-dirty',c.student||':'||c.season||':'||t.id,p.revision FROM bank t CROSS JOIN context c LEFT JOIN Records p ON p.kind='pbe-evidence-dirty' AND p.org_id=c.org AND p.id=c.student||':'||c.season||':'||t.id WHERE t.kind='pbe-target') SELECT kind||':'||id AS key,json_object('studentId',(SELECT student FROM context),'kind',kind,'id',id,'revision',revision) AS payload FROM guards WHERE kind||':'||id>? ORDER BY key LIMIT 128`,[...bound,w.workId,w.after],cooperationPageBudget(w));
}
/** Copy only D1 guard metadata, including expected sources for its exact-set classification. */
export async function captureSubjectD1Guards(scope:VerifiedCooperationScope,w:CooperationWork){
 const bound=args(scope,w),descriptor=w.descriptors[w.subjectIndex];
 if(!descriptor.complete)return [];
 return cooperationPage<{key:string;studentId:string;family:string;value:unknown}>(scope.ctx,`WITH ${personalContext},raw AS (SELECT m.id||':'||printf('%08d',e.key) AS key,json_extract(m.data,'$.family') AS family,e.value FROM context c JOIN Records m INDEXED BY Records_training_scope ON m.kind='pbe-chapter-manifest' AND m.org_id=c.org AND m.season_id=c.season AND m.owner_id=c.student AND json_extract(m.data,'$.generationId')=? JOIN json_each(m.data,'$.entries') e WHERE json_extract(m.data,'$.family') IN ('sources','guards','targets','heads','evidence')) SELECT key,json_object('key',key,'studentId',(SELECT student FROM context),'family',family,'value',json(CASE WHEN family='sources' THEN json_object('id',json_extract(value,'$.id'),'guards',json_extract(value,'$.guards')) WHEN family IN ('targets','heads') THEN json_extract(value,'$.guard') ELSE value END)) AS payload FROM raw WHERE key>? ORDER BY key LIMIT 128`,[...bound,descriptor.generationId,w.after],cooperationPageBudget(w));
}
