import {writeFile} from 'node:fs/promises';
import {expect} from 'vitest';
import {createNativeTestApp,TEST_ORG,TEST_USER} from '../test-runtime';
import {Store} from '../store';
import type {Env} from '../types';
import type {PbeQuestion} from './types';
import {sourceProof} from './bank';
export async function disputeFixture(label:string,options:{clock?:boolean;members?:number;questions?:number;parts?:number;measureAll?:boolean}={}){
 let now=Date.now();
 const meters:{bindingCalls:number;statements:number}[]=[],measurements:{path:string;status:number;bindingCalls:number;statements:number;durationMs:number}[]=[];
 const app=await createNativeTestApp({measureD1:true,replaceRoomAuthority:true,roomTestClock:options.clock,onD1Meter:m=>meters.push(m)});const store=new Store(app.db as unknown as Env['DB']),season=crypto.randomUUID(),pack=crypto.randomUUID(),source=crypto.randomUUID();
 await store.insert('practice-setting',TEST_ORG,TEST_ORG,{enabled:true});await store.insert('season',season,TEST_ORG,{id:season,organizationId:TEST_ORG,status:'Active',pbeEnabled:true});await store.insert('pack',pack,TEST_ORG,{id:pack,isActive:true,licensingStatus:'approved',sourceType:'Scripture'});
 const labels=['Alpha','Beta','Gamma','Delta','Epsilon','Zeta','Eta','Theta'].slice(0,options.parts??2);
 const unit={id:source,contentPackId:pack,bookKey:'GEN',chapter:1,verse:1,ordinal:1,citation:'Genesis 1:1',canonicalText:options.parts?labels.join(' and '):'Alpha and Beta',isActive:true};await store.insert('source',source,TEST_ORG,unit,{ownerId:pack});const range={bookKey:'GEN',startChapter:1,startVerse:1,endChapter:1,endVerse:1};await store.insert('scope',season,TEST_ORG,{contentPackId:pack,includes:[range],excludes:[]});
 const targets=labels.map((_,n)=>({id:crypto.randomUUID(),sourceUnitIds:[source],skill:'FactualRecall',label:`Label ${n}`}));for(const target of targets)await store.insert('pbe-target',target.id,TEST_ORG,target,{seasonId:season,ownerId:source});
 for(let n=0;n<(options.questions??10)+1;n++){const q:PbeQuestion={schemaVersion:2,id:crypto.randomUUID(),version:1,contentPackId:pack,sourceUnitId:source,sourceUnitIds:[source],sourceKind:'Scripture',reference:unit.citation,evidence:unit.canonicalText,kind:'List',prompt:`Name the labels, variant ${n}.`,ordered:false,parts:targets.map((t,i)=>({targetId:t.id,acceptedAnswers:[labels[i]],points:1}))};await store.insert('pbe-question-head',q.id,TEST_ORG,{id:q.id,seasonId:season,published:true,sourceFingerprint:await sourceProof(q,new Map([[source,unit]])),question:q},{seasonId:season,ownerId:source});}
 const players:{id:string;cookie:string}[]=[];for(let n=0;n<(options.members??4);n++){const id=crypto.randomUUID(),name=`dispute-player-${n}`;await app.db.prepare("INSERT INTO Users(id,org_id,user_name,display_name,kind,role,password_hash,credential_version) SELECT ?,org_id,?,?,'Student','Student',password_hash,credential_version FROM Users WHERE id=?").bind(id,name,name,TEST_USER).run();await store.insert('membership',`${season}:${id}`,TEST_ORG,{seasonId:season,userId:id,difficulty:'Advanced'},{seasonId:season,ownerId:id});await store.insert('assignment',crypto.randomUUID(),TEST_ORG,{seasonId:season,studentUserId:id,contentPackId:pack,...range},{seasonId:season,ownerId:id});const login=await app.fetch('/api/v1/auth/login',{method:'POST',headers:{Origin:'https://erudoza.test'},body:JSON.stringify({identifier:name,password:'Testing!123'})});players.push({id,cookie:login.headers.get('set-cookie')!.split(';')[0]});}
 const coach=(await app.login()).headers.get('set-cookie')!.split(';')[0];
 const call=async(actor:number,path:string,data?:unknown,headers:Record<string,string>={})=>{meters.splice(0);const at=performance.now();const response=await app.fetch('/api/v1'+path,{method:data?'POST':'GET',headers:{Cookie:actor===-1?coach:players[actor].cookie,Origin:'https://erudoza.test',...(options.clock?{'x-test-room-now':String(now)}:{}),...headers},...(data?{body:JSON.stringify(data)}:{})});if(options.measureAll||path.startsWith('/pbe/')||path.endsWith('/recap')){const total=meters.splice(0).reduce((a,b)=>({bindingCalls:a.bindingCalls+b.bindingCalls,statements:a.statements+b.statements}),{bindingCalls:0,statements:0});measurements.push({path,status:response.status,...total,durationMs:performance.now()-at});expect(total.statements).toBeLessThanOrEqual(50);await writeFile(new URL(`../../../../../.local/c3-dispute-meters-${label}.json`,import.meta.url),JSON.stringify(measurements,null,2));}return response;};
 const flagControl=async(enabled:boolean)=>{await app.db.prepare("UPDATE Records SET data=json_set(data,'$.enabled',json(?)),revision=revision+1 WHERE kind='practice-setting' AND id=?").bind(String(enabled),TEST_ORG).run();};
 return {app,store,season,players,coach,call,flagControl,measurements,targets,labels,advance:(ms:number)=>{now+=ms;},get now(){return now;}};
}
