// @vitest-environment node
import {afterEach,expect,it} from 'vitest';
import {writeFile} from 'node:fs/promises';
import {disputeFixture} from './dispute-fixture';
import {TEST_ORG,TEST_USER} from '../test-runtime';
import type {PracticeRoom,PracticeBootstrap,PbeDispute} from '../../../src/api/practice';
import type {Room} from '../practice/state';
let fixture:Awaited<ReturnType<typeof disputeFixture>>;
afterEach(async()=>{await fixture?.app.runtime.dispose();});
it.each([[1,false],[2,false],[2,true]] as const)('finishes90 PBE questions with %i six-student teams, pending review, scribe rotation and socket reconnect before a later correction',async(teams,threshold)=>{
 fixture=await disputeFixture(`fix1-full90-${teams}-${threshold}`,{clock:true,members:teams*6,questions:90,measureAll:true});const f=fixture,base=`/organizations/${TEST_ORG}/practice`,owner=teams===1?-1:0;
 const response=await f.call(owner,base+'/rooms',{seasonId:f.season,format:'Pbe',teamCount:teams,teamSize:6,questionCount:90});expect(response.status).toBe(200);let room=await response.json() as PracticeRoom;
 const command=async(actor:number,action:string,extra:Record<string,unknown>={})=>{const input={commandId:crypto.randomUUID(),revision:room.revision,action,...extra};const r=await f.call(actor,`${base}/rooms/${room.id}/commands`,input);expect(r.status,await r.clone().text()).toBe(200);room=await r.json() as PracticeRoom;return input;};
 const refresh=async()=>{const r=await f.call(0,`${base}/rooms/${room.id}`);expect(r.status,await r.clone().text()).toBe(200);room=await r.json() as PracticeRoom;};
 for(let n=teams===1?0:1;n<f.players.length;n++){await command(owner,'invite',{targetUserId:f.players[n].id,...(teams===2?{team:Math.floor(n/6)+1}:{})});const inbox=await (await f.call(n,base+'/bootstrap')).json() as PracticeBootstrap;expect(inbox.invitations[0].teamCount).toBe(teams);const accepted=await f.call(n,`${base}/invitations/${inbox.invitations[0].id}/accept`,{team:Math.floor(n/6)+1});expect(accepted.status).toBe(200);room=await accepted.json() as PracticeRoom;}
 for(let n=0;n<f.players.length;n++)await command(n,'ready');await command(0,'start');let breaks=0,dispute:PbeDispute|undefined,firstAccepted:string|undefined;const scribes=Array.from({length:teams},(_,team)=>team*6);
 const socket=async()=>{const r=await f.app.fetch('/api/v1'+base+`/rooms/${room.id}/socket`,{headers:{Cookie:f.players[0].cookie,Origin:'https://erudoza.test',Upgrade:'websocket','x-test-room-now':String(f.now)}});expect(r.status).toBe(101);r.webSocket!.accept();return r.webSocket!;};let connection=await socket();
 for(let q=0;q<90;q++){
  if(q){if(q===15)for(let team=0;team<teams;team++){scribes[team]=team*6+1;await command(team*6,'scribe',{targetUserId:f.players[scribes[team]].id});}f.advance(10000);await refresh();if(room.phase==='Break'){breaks++;expect(q).toBe(45);expect(room.question).toBeNull();f.advance(300000);await refresh();}}
  expect(room.phase).toBe('Presentation');expect(room.questionIndex).toBe(q);const questionId=room.question!.id;
  if(q===16){connection.close(1000);connection=await socket();await refresh();expect(room.question!.id).toBe(questionId);}
  for(let team=0;team<teams;team++)await command(scribes[team],'present',{questionId,delivery:team===0?'TextFallback':'Audio'});
  expect(room.phase).toBe('Scheduled');const starts=Date.parse(room.responseStartsAt!);expect(starts-f.now).toBe(3000);f.advance(3000);
  for(let team=0;team<teams;team++){const answers=team===0&&(q===0||threshold&&q>80)?(threshold?(q===81?['Alpha','wrong']:['wrong','wrong']):['Alpha','wrong']):['Alpha','Beta'];if(q===8)await command(scribes[team],'draft',{questionId,answers});const input=await command(scribes[team],'submit',{questionId,answers});if(q===8){const retry=await f.call(scribes[team],`${base}/rooms/${room.id}/commands`,input);expect(retry.status).toBe(200);}}
  expect(room.phase).toBe('Review');
  if(q===0){const result=room.results.find(r=>r.team===1)!;firstAccepted=JSON.stringify({attemptId:result.attemptId,answers:result.answers,responseLockedAtMs:result.responseLockedAtMs,accuracyHundredths:result.accuracyHundredths});const flagged=await f.call(0,'/pbe/disputes',{activity:'Team',sessionId:room.id,attemptId:result.attemptId,reason:'Please check the second label later'});expect(flagged.status).toBe(201);dispute=await flagged.json() as PbeDispute;await refresh();expect(room.provisional).toBe(true);expect(room.results.find(r=>r.team===1)!.accuracyHundredths).toBe(threshold?0:100);expect((await f.call(0,'/pbe/disputes',{activity:'Team',sessionId:room.id,attemptId:result.attemptId,reason:'Please check the second label later'})).status).toBe(200);}
 }
 connection.close(1000);f.advance(10000);await refresh();expect(room.status).toBe('Completed');expect(breaks).toBe(1);expect(room.results).toHaveLength(90*teams);expect(room.pendingCount).toBe(1);
 for(let n=0;n<100&&!await f.store.get('match',room.id,TEST_ORG);n++){f.advance(5000);const published=await f.call(0,`${base}/rooms/${room.id}`,undefined,{'x-test-room-alarm':'1'});expect(published.status,await published.clone().text()).toBe(200);}expect(await f.store.get('match',room.id,TEST_ORG)).not.toBeNull();
 const replay=await f.call(0,base+'/rooms',{seasonId:f.season,format:'Pbe',teamCount:teams,teamSize:6,questionCount:90});expect(replay.status).toBe(200);
 const bootstrap=await (await f.call(0,base+'/bootstrap')).json() as PracticeBootstrap;expect(bootstrap.achievements.map(a=>a.key)).toContain('pbe-team-v1:rehearsal-complete');expect(bootstrap.trends![0]).toMatchObject({matches:1,pendingCount:1,accuracyHundredths:threshold?16100:17800,availableHundredths:17800,distinctQuestions:90,distinctPassages:1});
 if(threshold)expect(bootstrap.achievements.map(a=>a.key)).not.toContain('pbe-team-v1:team-precision');if(teams===2){const other=await(await f.call(6,base+'/bootstrap')).json() as PracticeBootstrap;expect(other.achievements.map(a=>a.key)).toContain('pbe-team-v1:team-precision');}
 const queue=await (await f.call(-1,'/pbe/disputes')).json() as {items:PbeDispute[]};expect(queue.items).toContainEqual(expect.objectContaining({id:dispute!.id,questionVersion:1,partPoints:[1,1]}));
 const path='/pbe/disputes/'+encodeURIComponent(dispute!.id)+'/resolve',resolution={expectedRevision:1,pointsByPart:threshold?[0,0]:[1,1],reason:'Frozen source ruling'};const resolved=await f.call(-1,path,resolution);expect(resolved.status,await resolved.clone().text()).toBe(200);expect(await (await f.call(-1,path,resolution)).json()).toEqual(await resolved.json());await refresh();expect(room.provisional).toBe(false);expect(room.scores[0].accuracyHundredths).toBe(threshold?16100:18000);
 const after=await (await f.call(0,base+'/bootstrap')).json() as PracticeBootstrap;expect(after.achievements.filter(a=>a.key==='pbe-team-v1:team-precision')).toHaveLength(threshold?0:1);expect(await f.store.list('pbe-grade-adjustment',TEST_ORG,{seasonId:f.season})).toHaveLength(1);expect(await f.store.list('mastery-honor',TEST_ORG,{ownerId:f.players[0].id})).toEqual([]);
 const raw=await (await f.app.fetch('/api/v1'+base+`/rooms/${room.id}`,{headers:{Cookie:f.players[0].cookie,Origin:'https://erudoza.test','x-test-room-now':String(f.now),'x-test-room-snapshot':'1'}})).json() as Room;const first=raw.submissions[0];expect(JSON.stringify({attemptId:first.attemptId,answers:first.answers,responseLockedAtMs:first.responseLockedAtMs,accuracyHundredths:first.accuracyHundredths})).toBe(firstAccepted);expect(raw.submissions.every(s=>s.speedHundredths===0&&s.attemptId&&s.responseLockedAtMs)).toBe(true);
 await writeFile(new URL(`../../../../../.local/c3-fix1-native-full90-${teams}-${threshold}.json`,import.meta.url),JSON.stringify(raw));await writeFile(new URL(`../../../../../.local/c3-fix1-native-full90-size-${teams}-${threshold}.json`,import.meta.url),JSON.stringify({questions:raw.questions.length,reserves:raw.reserves.length,roster:raw.members.length,finals:raw.submissions.length,utf8Bytes:new TextEncoder().encode(JSON.stringify(raw)).length,status:raw.status,resolvedBy:TEST_USER}));
},120000);
