// <auto-generated />
using System;
using Erudoza.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Erudoza.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ErudozaDbContext))]
    [Migration("20260910210819_BuiltInNkjvLibrary")]
    partial class BuiltInNkjvLibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Erudoza.Domain.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Erudoza.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("OrganizationId", "SeasonId", "StudentUserId", "Type");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Erudoza.Domain.AssignmentScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndVerse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartVerse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ContentPackId");

                    b.ToTable("AssignmentScopes");
                });

            modelBuilder.Entity("Erudoza.Domain.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChallengeCardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSubmissionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluationResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluatorVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HintsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLegacyDuplicate")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KnowledgeUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeCardId")
                        .IsUnique()
                        .HasFilter("[IsLegacyDuplicate] = 0");

                    b.HasIndex("SessionId", "ClientSubmissionId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "StudentUserId", "SeasonId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("Erudoza.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CreatedAtUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("Erudoza.Domain.ChallengeCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerKeyJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnswerMode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AnswerSourceUnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvaluatorVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgeUnitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceUnitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeUnitId");

                    b.HasIndex("SourceUnitId");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("ChallengeCards");
                });

            modelBuilder.Entity("Erudoza.Domain.CompetitionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "SeasonId", "UserId")
                        .IsUnique();

                    b.ToTable("CompetitionMembers");
                });

            modelBuilder.Entity("Erudoza.Domain.CompetitionScopeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndVerse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("StartChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartVerse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("OrganizationId", "SeasonId");

                    b.ToTable("ScopeEntries");
                });

            modelBuilder.Entity("Erudoza.Domain.CompetitionSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("TargetCompetitionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleProfileId");

                    b.HasIndex("OrganizationId", "Name");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Erudoza.Domain.ContentPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PackKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "PackKey", "Version")
                        .IsUnique();

                    b.ToTable("ContentPacks");
                });

            modelBuilder.Entity("Erudoza.Domain.GenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GenerationJobs");
                });

            modelBuilder.Entity("Erudoza.Domain.KnowledgeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackId");

                    b.HasIndex("SourceUnitId", "Kind")
                        .IsUnique();

                    b.ToTable("KnowledgeUnits");
                });

            modelBuilder.Entity("Erudoza.Domain.MasteryState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExactWordingScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FactualRecallScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KnowledgeUnitId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecognitionScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "StudentUserId", "SeasonId", "KnowledgeUnitId")
                        .IsUnique();

                    b.ToTable("MasteryStates");
                });

            modelBuilder.Entity("Erudoza.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Erudoza.Domain.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("Erudoza.Domain.PlayableQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionCandidateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionCandidateId");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("PlayableQuestions");
                });

            modelBuilder.Entity("Erudoza.Domain.PracticeAwardRecord", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReconciledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("OrganizationId", "SeasonId", "UserId", "Key");

                    b.ToTable("PracticeAwardRecord");
                });

            modelBuilder.Entity("Erudoza.Domain.PracticeQuestionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "QuestionKey", "Version")
                        .IsUnique();

                    b.ToTable("PracticeQuestionRecord");
                });

            modelBuilder.Entity("Erudoza.Domain.PracticeRoomRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("PracticeRoomRecord");
                });

            modelBuilder.Entity("Erudoza.Domain.PracticeSetting", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrganizationId");

                    b.ToTable("PracticeSetting");
                });

            modelBuilder.Entity("Erudoza.Domain.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PromptVersions");
                });

            modelBuilder.Entity("Erudoza.Domain.QuestionCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedAnswersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AnswerMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratorVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Status");

                    b.ToTable("QuestionCandidates");
                });

            modelBuilder.Entity("Erudoza.Domain.QuestionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionCandidateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceUnitId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionCandidateId");

                    b.HasIndex("SourceUnitId");

                    b.ToTable("QuestionEvidence");
                });

            modelBuilder.Entity("Erudoza.Domain.ReviewSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KnowledgeUnitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId", "DueAtUtc");

                    b.HasIndex("OrganizationId", "StudentUserId", "SeasonId", "KnowledgeUnitId")
                        .IsUnique();

                    b.ToTable("ReviewSchedules");
                });

            modelBuilder.Entity("Erudoza.Domain.RuleProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("RuleProfiles");
                });

            modelBuilder.Entity("Erudoza.Domain.SourceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalBookKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackId");

                    b.ToTable("SourceDocuments");
                });

            modelBuilder.Entity("Erudoza.Domain.SourceUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CitationLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentPackId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensingMetadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedComparisonText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceDocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Verse")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("SourceDocumentId");

                    b.HasIndex("ContentPackId", "BookKey", "Chapter", "Verse")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "BookKey", "Chapter", "Verse");

                    b.ToTable("SourceUnits");
                });

            modelBuilder.Entity("Erudoza.Domain.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("Erudoza.Domain.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DifficultyPolicyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleProfileSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetCardCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("OrganizationId", "StudentUserId", "SeasonId", "Status");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("Erudoza.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Erudoza.Domain.Assignment", b =>
                {
                    b.HasOne("Erudoza.Domain.CompetitionSeason", "Season")
                        .WithMany("Assignments")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Erudoza.Domain.AssignmentScope", b =>
                {
                    b.HasOne("Erudoza.Domain.Assignment", "Assignment")
                        .WithMany("Scopes")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.ContentPack", "ContentPack")
                        .WithMany()
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("Erudoza.Domain.Attempt", b =>
                {
                    b.HasOne("Erudoza.Domain.ChallengeCard", "ChallengeCard")
                        .WithMany()
                        .HasForeignKey("ChallengeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.StudySession", "Session")
                        .WithMany("Attempts")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengeCard");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Erudoza.Domain.ChallengeCard", b =>
                {
                    b.HasOne("Erudoza.Domain.KnowledgeUnit", "KnowledgeUnit")
                        .WithMany()
                        .HasForeignKey("KnowledgeUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.StudySession", "Session")
                        .WithMany("Cards")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.SourceUnit", "SourceUnit")
                        .WithMany()
                        .HasForeignKey("SourceUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeUnit");

                    b.Navigation("Session");

                    b.Navigation("SourceUnit");
                });

            modelBuilder.Entity("Erudoza.Domain.CompetitionMember", b =>
                {
                    b.HasOne("Erudoza.Domain.CompetitionSeason", "Season")
                        .WithMany("Members")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("Erudoza.Domain.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Erudoza.Domain.CompetitionScopeEntry", b =>
                {
                    b.HasOne("Erudoza.Domain.ContentPack", "ContentPack")
                        .WithMany()
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.CompetitionSeason", "Season")
                        .WithMany("ScopeEntries")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentPack");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Erudoza.Domain.CompetitionSeason", b =>
                {
                    b.HasOne("Erudoza.Domain.Organization", "Organization")
                        .WithMany("Seasons")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.RuleProfile", "RuleProfile")
                        .WithMany()
                        .HasForeignKey("RuleProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("RuleProfile");
                });

            modelBuilder.Entity("Erudoza.Domain.ContentPack", b =>
                {
                    b.HasOne("Erudoza.Domain.Organization", "Organization")
                        .WithMany("ContentPacks")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Erudoza.Domain.KnowledgeUnit", b =>
                {
                    b.HasOne("Erudoza.Domain.ContentPack", "ContentPack")
                        .WithMany()
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.SourceUnit", "SourceUnit")
                        .WithMany("KnowledgeUnits")
                        .HasForeignKey("SourceUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentPack");

                    b.Navigation("SourceUnit");
                });

            modelBuilder.Entity("Erudoza.Domain.OrganizationMember", b =>
                {
                    b.HasOne("Erudoza.Domain.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.ApplicationUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Erudoza.Domain.PlayableQuestion", b =>
                {
                    b.HasOne("Erudoza.Domain.QuestionCandidate", "QuestionCandidate")
                        .WithMany()
                        .HasForeignKey("QuestionCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionCandidate");
                });

            modelBuilder.Entity("Erudoza.Domain.QuestionEvidence", b =>
                {
                    b.HasOne("Erudoza.Domain.QuestionCandidate", "QuestionCandidate")
                        .WithMany("Evidence")
                        .HasForeignKey("QuestionCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.SourceUnit", "SourceUnit")
                        .WithMany()
                        .HasForeignKey("SourceUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionCandidate");

                    b.Navigation("SourceUnit");
                });

            modelBuilder.Entity("Erudoza.Domain.SourceDocument", b =>
                {
                    b.HasOne("Erudoza.Domain.ContentPack", "ContentPack")
                        .WithMany("Documents")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentPack");
                });

            modelBuilder.Entity("Erudoza.Domain.SourceUnit", b =>
                {
                    b.HasOne("Erudoza.Domain.ContentPack", "ContentPack")
                        .WithMany("SourceUnits")
                        .HasForeignKey("ContentPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.SourceDocument", "SourceDocument")
                        .WithMany("Units")
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentPack");

                    b.Navigation("SourceDocument");
                });

            modelBuilder.Entity("Erudoza.Domain.StudentProfile", b =>
                {
                    b.HasOne("Erudoza.Domain.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.ApplicationUser", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Erudoza.Domain.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Erudoza.Domain.StudySession", b =>
                {
                    b.HasOne("Erudoza.Domain.CompetitionSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Erudoza.Domain.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");

                    b.Navigation("Season");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Erudoza.Domain.Team", b =>
                {
                    b.HasOne("Erudoza.Domain.CompetitionSeason", "Season")
                        .WithMany("Teams")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Erudoza.Domain.ApplicationUser", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Erudoza.Domain.Assignment", b =>
                {
                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("Erudoza.Domain.CompetitionSeason", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Members");

                    b.Navigation("ScopeEntries");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Erudoza.Domain.ContentPack", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SourceUnits");
                });

            modelBuilder.Entity("Erudoza.Domain.Organization", b =>
                {
                    b.Navigation("ContentPacks");

                    b.Navigation("Members");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("Erudoza.Domain.QuestionCandidate", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Erudoza.Domain.SourceDocument", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Erudoza.Domain.SourceUnit", b =>
                {
                    b.Navigation("KnowledgeUnits");
                });

            modelBuilder.Entity("Erudoza.Domain.StudySession", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
